pyroute2/iwutil.py
Add the connect to ap and disconnect ap
This function return nothing: I use the self.put because nlm_request wait a response
To be sure that the device is successful is connected , the only way is to monitoring the nl80211 event and catch the CONNECTED event
=> Add connect and disconnect to an ap

pyroute2/ipdb/interface.py
Currently the following work:
~~~python
eno1.add_ip('10.10.0.8/24')
eno1.add_ip('10.10.0.8/255.255.255.0')
eno1.add_ip('10.10.0.8', mask=24)
~~~
but this one doesn't
~~~python
eno1.add_ip('10.10.0.8', mask='255.255.255.0')
~~~
This patch makes it easier to integrate the dhcp support:
~~~python
reply = dhcp('eno1')
yiaddr = reply['yiaddr']
subnet_mask = reply['options']['subnet_mask']
with eno1:
eno1.add_ip(yiaddr, mask=subnet_mask)
~~~
As the subnet_mask comes in dotted quad notation.
=> Allow mask positional argurment to also accept dotted quad notation

pyroute2/netlink/nl80211/__init__.py
This pull request does the following tasks:
- Correct the `TypeError` while printing out the `NL80211_BSS_INFORMATION_ELEMENTS` attribute
- Add traffic indication map (`NL80211_BSS_ELEMENTS_TIM`) and extended supported rate (`NL80211_BSS_ELEMENTS_EXTENDED_RATE`) in the scan results
=> Improvement for iw.scan()

pyroute2/iwutil.py
This pull request add parameter `ifindex` to the `leave_ibss` so that specific interface is able to leave the mesh network.
=> add ifindex to leave_ibss

pyroute2/netlink/nl80211/__init__.py
It is targeting to solve the null terminator at the end of SSID revealing by `iw dev`. https://github.com/svinota/pyroute2/issues/144
=> Change type of ATTR_SSID to string

pyroute2/iproute.py, pyroute2/netlink/rtnl/tcmsg.py, tests/test_tc.py, tests/utils.py
This change requires at least the bpf syscall (linux >4.0 or so, CONFIG_BPF_SYSCALL=y) as well as option CONFIG_NET_CLS_BPF=m/y. A similar feature is going into iproute2 net-next branch (http://git.kernel.org/cgit/linux/kernel/git/shemminger/iproute2.git?h=net-next)
To effectively use this feature, one needs to have opened a BPF program and have an open fd handle to give to the tc filter. Doing that is outside the scope of this commit, and other tools are in progress to support this. This commit includes a test case which exercises the feature without creating a dependency on those tools.
=> Add BPF filter support to tcmsg

pyroute2/netlink/rtnl/tcmsg.py, tests/test_tc.py
* BPF filter can support POLICER type, similar to u32 option format
* Add test case for policer
=> Add support for policer to bpf filter

pyroute2/iwutil.py
Previously we ignored the CHANNEL_WIDTH attribute for all widths under 40 MHz, which defaults them all to 20 MHz No-HT. This pull request will set them to the correct value.
=> Set ChanWidth for Join IBSS even if below 40 MHz

pyroute2/netns/nslink.py
By default, pressing Ctrl-C on the keyboard when running a python
process in the foreground sends SIGINT to all processes in the
hierarchy, which results in the cleanup+wait of the parent waiting on
some message from the child, which is also cleaning itself up. To avoid
this, mask SIGINT in the children. This places a burden on the parent to
always wait on the child, but avoids the deadlock.
Signed-off-by: Brenden Blanco <bblanco@plumgrid.com>
=> Mask SIGINT from netns child processes

pyroute2/netlink/rtnl/ifinfmsg.py
This option was combined with the IFLA_VXLAN_COLLECT_METADATA option,
and the FLOWBASED flag is removed from net-next before merging with
-stable branch. Hopefully there are no more changes in the enum.
See https://patchwork.ozlabs.org/patch/503901/
Signed-off-by: Brenden Blanco <bblanco@plumgrid.com>
=> Remove IFLA_VXLAN_FLOWBASED flag from ifinfmsg

pyroute2/iwutil.py
This is a flag, so it has a payload of NULL in the netlink `nla_put_flag` command. We previously were not setting this flag, which resulted in off-channel scans despite us setting a fixed frequency.
=> Actually set the FREQ_FIXED flag

pyroute2/netlink/__init__.py
Converted catching AssertionError to normal if statements. Asserts should not be used for this kind of purpose (program flow control).
We got a tremendous performance improvement (run time dropped from 70 seconds to 3 seconds) after doing this fix on Python 2.x & Py.test based device protocol tester. Py.test does "assertion rewriting" ( http://pybites.blogspot.fi/2011/07/behind-scenes-of-pytests-new-assertion.html ) when an assertion error is encountered in addition to normal call stack tracing. This seems to slow down the program quite a lot.
=> Don't use assertions for flow control

pyroute2/netlink/__init__.py, pyroute2/netlink/rtnl/ifinfmsg.py
Adds some more recent routing attributes:
- `IFLA_PHYS_SWITCH_ID`
- `IFLA_LINK_NETNSID`
- `IFLA_PHYS_PORT_NAME`
All indications show that `IFLA_LINK_NETNSID` is signed but I could be wrong.
=> Add more routing attributes

pyroute2/netlink/nl80211/__init__.py
This matches the kernel headers in 4.2 (and is backwards compatible): http://lxr.free-electrons.com/source/include/uapi/linux/nl80211.h#L3332
This also fixes #134 
It adds the BSS_STATUS information (when we're associated), BSS_SIGNAL_MBM (for signal strength), and correctly decodes SEEN_MS and CHAN_WIDTH.
=> Update NL80211_BSS nla_map for 4.2 kernel

pyroute2/netlink/__init__.py
There was an incomplete revert of commits on Aug 11:
https://github.com/svinota/pyroute2/commit/7b27abd65f3a40405f5618370ade113fc2806c6a
https://github.com/svinota/pyroute2/commit/16a8aced82c65b94eb9e15a7d773a3256763d155
We had trouble decoding NL80211_BSS_INFORMATION_ELEMENTS until I removed these two lines and completed the revert. Many of the information elements were incomplete or incorrect - this pull request fixes that.
=> Remove hanging code from reverted commit

pyroute2/iproute.py, tests/general/test_rule.py
This would allow for inserting iproute2 rules with masked `fwmark` parameters as discussed in #187
=> Handling FRA_FWMASK parameter when calling IPRoute.rule()

pyroute2/iproute.py
- Add some documentation to for quick-reference on creating `tc` filters for matching on source *or* destination IP/subnet.
- Bit offsets were discovered by using `tc` to add filters via CLI, assessing the output, and re-creating with pyroute2.
- Fixes #185 
1. ~~Resolve merge conflict~~
1. ~~This example is only applicable for interfaces, such as [IMQ]() devices~~
*@svinota requests this being annotated in the docstring* *(See [a7f83955](https://github.com/tomislacker/pyroute2/commit/a7f83955d6c159785835b3234f7594118273a3cb))*
If you're using classes/qdiscs that aren't available for upstream traffic control, I believe filter additions will be rejected by the kernel that match on destination host and have their `target` set to such a class/qdisc
=> WIP: Add example tc add-filter for IP & subnet matching on src/dst

pyroute2/common.py, tests/general/test_ipdb.py
Current implementation of `__getattribute__` in Dotkeys doesn't throw AttributeError if a requested attribute cannot be found. Instead, `KeyError` is thrown and it breaks hasattr as the latter determines non-existence of an attribute by [catching](https://github.com/python/cpython/blob/master/Python/bltinmodule.c#L1051) `AttributeError`.
The change enables rpyc & pyroute2 interopability to manage network on a remote system.
=> make Dotkeys compliant with hasattr protocol

pyroute2/iproute.py, pyroute2/netlink/rtnl/__init__.py, pyroute2/netlink/rtnl/tcmsg.py
In linux 4.5, a new clsact qdisc type is added, which is very similar to
ingress but can also apply to egress packets in a lightweight (lockless)
way.
Also improving performance is the direct-action flag for bpf filters, in
which a program directly returns the action (drop, pass, redirect, etc.)
to take in the classifer.
=> Add tc clsact and bpf filter direct-action support

pyroute2/netlink/rtnl/rtmsg.py
RTA_FLOW is defined as unsigned 32b number, consisting of two 16 bit
fields to distinguish source/destination realms. Related code in
iproute2 to interpret the value:
```
if (tb[RTA_FLOW] && filter.realmmask != ~0U) {
__u32 to = rta_getattr_u32(tb[RTA_FLOW]);
__u32 from = to>>16;
to &= 0xFFFF;
fprintf(fp, "realm%s ", from ? "s" : "");
if (from) {
fprintf(fp, "%s/",
rtnl_rtrealm_n2a(from, b1, sizeof(b1)));
}
fprintf(fp, "%s ",
rtnl_rtrealm_n2a(to, b1, sizeof(b1)));
}
```
The following snippet
```
ipr = pyroute2.IPRoute()
r = pyroute2.IPRouteRequest({'family': socket.AF_INET, 'dst': \
"192.168.0.0", 'mask': 24, "gateway": "10.42.6.1", "flow": 45})
ipr.route("add", **r)
```
fails with
```
File "./test.py", line 7, in <module>
ipr.route("add", **r)
File …
```
=> Change the RTA_FLOW data type to uint32

.gitignore, tests/run.sh, tox.ini
The easiest way to run tests with all versions of python is "tox".
It looks like this:
```
pyenv shell 2.6.9 2.7.11 3.3.6 3.4.4 3.5.1
tox
```
Tests will be run sequentially for each of the python versions.
However tests can also be run in a specific pyenv environment without
tox:
```
pyenv virtualenv 3.3.6 pyroute2-py33
pyenv activate pyroute2-py33
make test
```
`make test` can still use python that comes from linux distribution.
=> Add tox and make tests/run.sh agnostic to pyenv wrappers.

tests/general/test_ipdb.py, tests/utils.py
`require_bond` and `require_bridge` pass a `nlmsg` to `compat_xxx_yyy` functions instead of `str`as their former implementation didin't work (indeed `compat_xxx_yyy` expects a `nlmsg`).
Presence of `__init__.py` under tests directory didn't allow to run individual tests (i.e. `nosetests path/to/module.py:Class.method`), hence the `__init__.py` was deleted.
=> tests: skip bonding/bridge/mpls tests properly.

pyroute2/netlink/nl80211/__init__.py, tests/general/test_ipr.py, tests/run.sh, tox.ini
I'm trying to make all tests pass on supported versions of python. Some of the tests aren't intended to pass on very old kernels (<4).
I'm about to get all tests passing on Python 2.x. Probably there will be couple more changesets to fix issues on Python 3.x.
py32 tox environment is dropped as pip doesn't support Python 3.0-3.2.
=> Skip tests on the old kernels

pyroute2/ipdb/interface.py
Python 3 has stricter comparison rules for None than Python 2 (i.e. None
cannot be compared with None, as TypeError is raised). We cannot rely on
sorted function for keys that might contain None. Therefore we sort only
ip addresses with non-None flags and then append addresses with empty
flags to the end.
=> ipdb: don't sort ipaddrs with empty flags.

pyroute2/ipdb/interface.py, pyroute2/ipdb/main.py, tests/general/test_ipdb.py, tox.ini
Kernel headers [prescribe](http://lxr.free-electrons.com/source/include/uapi/linux/if_addr.h?v=3.14#L22) to ignore `ifa_flags` field, only if `IFA_FLAGS` attribute is present.
=> use flags field if IFA_FLAGS attribute is not present in a NLA

pyroute2/netlink/rtnl/ifinfmsg.py
Linux introduced GTP interface not that long ago and this enables pyroute2 to support bringing up the interface. This only implements ifinfmsg level support.
=> Added support for GTP interface

pyroute2/netlink/nl80211/__init__.py
The code didn't account for the fact that length specified
in IE's header doesn't include the size of the header itself.
So when iterating over elements, you should increment pointer
by "2 + length", not by just "length".
This bug caused incorrect IEs parsing, and infinite loops
if array happens to contain zero-length IE (which was my case).
As a further proof, here's the source of iw tool, which is
probably correct:
http://git.sipsolutions.net/?p=iw.git;a=blob;f=scan.c;h=a942769dbc3e4f6a48d0e9e902298934a93332d8;hb=HEAD#l1830
=> fixed incorrect nl80211 BSS_ELEMENTS handling

pyroute2/netlink/nl80211/__init__.py
It had both off-by-one and completely incorrect offset.
=> fixed problems with supported rate parsing

pyroute2/netlink/nfnetlink/ipset.py
ADT messages have the same standard attributes than CADT messages, but
some values overlap (attributes > 16, see IPSET_ATTR_CADT_MAX in
ip_set.h).
This patch split the two kind of messages for the parsing, allowing to
read the real attributes with the list messages. For example,
IPSET_ATTR_BYTES and IPSET_ATTR_PACKETS are now available.
=> ipset: fix parsing of ADT attributes

README.packages.md, packages/RedHat/python-pyroute2.spec
To successfully build on both EPEL and Fedora for Python3 there's some
macros that need to be used. This patch puts them in the specfile and
updates to the latest release.
Signed-off-by: Antoni Segura Puimedon <antonisp@celebdor.com>
=> packaging: Support 0.4.x on both EPEL and Fedora

pyroute2/netlink/ipq/__init__.py
IPQ used debricated msg.buf.getvalue() and this changes it to use msg.data that I believe to be the right way today
=> Updated message data buffer reference

pyroute2/netns/__init__.py, pyroute2/netns/nslink.py, tests/general/test_netns.py
If the netns argument to the NetNS constructor is the path of an
existing file, that is interpreted as the full namespace path, and
not appended to netns.NETNS_RUN_DIR.
This patch add a setns_from_path function to the netns module.
This function simply opens the namespace, perform the setns syscall,
and returns the file descriptor. In order to avoid code duplication
the setns function now calls setns_from_path
A test has been added to validate creating a NetNS object using the
path of an existing namespace.
Creating or deleting namespaces using a full path has not been
implemented as a part of this patch.
=> NetNS: Allow full namespace path in constructor

pyroute2/netlink/taskstats/__init__.py
Python's built in padding doesn't work in this case because we have a
4-byte field with __attribute__((aligned(8))) specified on it.
=> The ac_uid field is aligned on an 8-byte boundary: pad to suit it

pyroute2/netlink/__init__.py, pyroute2/netlink/nlsocket.py, pyroute2/netlink/rtnl/iprsocket.py
From netlink documentation:
NETLINK_LISTEN_ALL_NSID (since Linux 4.2)
When set, this socket will receive netlink notifications from all network namespaces that have an nsid assigned into the network namespace where the socket has been opened.  The nsid is sent to user space via an ancillary data.
=> support NETLINK_LISTEN_ALL_NSID netlink option

pyroute2/ipdb/interface.py, pyroute2/ipdb/linkedset.py, pyroute2/ipdb/main.py, tests/general/test_ipdb.py
Primary and secondary addresses depend on the order in which they are added to an interface [1] .  This commit makes pyroute2 add IP addresses in the same order Interface.add_ip is called. This is achieved by changing LinkedSet.raw from a plain dict to an OrderedDict and reimplementing set set operators in IPaddrSet. The `reload` function reloads all addresses from the kernel.  This also lets `pyroute2` reload the order primary and secondary addresses on interfaces. (More details in the commit messages.)
[1] iproute2 docs: http://baturin.org/docs/iproute2/#Notes
=> Sort addresses in IPaddrSet

pyroute2/iproute.py, pyroute2/netlink/rtnl/tcmsg/sched_htb.py
When we call `tc` function for creating the HTB QDisc with NO kwargs,
the kernel will return error 22 (invalid argument):
ip.tc("add", "htb", eth0, 0x10000)
pyroute2.netlink.exceptions.NetlinkError: (22, 'Invalid argument')
As you can see by calling the `tc` function without any additional
arguments (we only defined `command`, `kind`, `index` and `handle`
arguments) the module will raise `NetlinkError`; reason: according to
'net/sched/sch_htb.c' of linux kernel source code, to create a HTB
QDisc we also need to define `direct_pkts`, `rate2quantum` and
`defcls` which is not defined by default (the function
`get_parameters` is responsible for providing these default arguments
which WON'T be called unless we have at least ONE argument in kwargs.
with '#' will be ignored, and an empty message …
=> Bugfix: Fix HTB QDisc Generation With Default Arguments

pyroute2/ipdb/main.py
IPDB listens to all netlink updates by default.  Some applications
might not require information about all netlink-managed entities.
Filtering the messages that the kernel sends IPDB alleviates CPU use
and might prevent buffer overflow errors that happen during netlink
broadcast storms.
Our use case is that we observed buffer overflows when using IPDB to manage IP addresses and IP rules on a server having a large number of full routing tables. To test these changes (and make the problem reproducible), I created a [C program to create netlink storms][1] and used the simple script below. Without filtering route messages, it causes buffer overflows on pyroute instantly, in 100% of the tests I ran. Filtering route updates, no overflows were observed.
[1]: …
=> let users choose RTNL groups IPDB listens to

pyroute2/netns/__init__.py
import os
os.uname()
('Linux', 'Mustang0', '4.9.0-rc3-00011-g13c5a1f', '#4 SMP PREEMPT Fri Dec 9 08:47:26 CST 2016', 'aarch64')
os.uname()[4]
'aarch64'`
Signed-off-by: Zhiyi Sun <zhiyisun@gmail.com>
=> Fix machine name and syscall number of aarch64(arm 64-bit)

pyroute2/ipdb/interface.py, pyroute2/iproute.py, pyroute2/netlink/rtnl/ifinfmsg/__init__.py, pyroute2/netlink/rtnl/req.py, tests/general/test_ipdb.py
'ip6gre' is implemented in the kernel using the same IFLA_GRE_XXX
fields as GRE over IPv4, but with IPv6 instead of IPv4 addresses
in the 'local' and 'remote' slots.
This patch adds an NLA map for ip6gre with the appropriate support.
Since the field names would conflict with the existing IFLA_GRE
ones, these new items are prefixed IFLA_IP6GRE instead.
I did experiment with using the same, existing, NLA map for both
address families. Unfortunately the 'target' type requires the address
family to be specified in both directions; to and from the kernel.
This can be achieved when creating GRE links; however the only way
I see of reconstructing the addresses from the kernel is to add a
heuristic to the 'target' type to guess the family; this did not
feel like the correct approach.
In the end, …
=> Add support for GRE over IPv6

packages/RedHat/python-pyroute2.spec
It it time to publish 0.4.13 in EL and fedora
Signed-off-by: Antoni Segura Puimedon <antonisp@celebdor.com>
=> redhat packaging: bump version to 0.4.13

pyroute2/netlink/rtnl/tcmsg/cls_u32.py, tests/general/test_tc.py
Hello,
I noticed the u32 filter returned the stats2 class instead of an instance for its `TCA_ACT_STATS` member. As a result, it crashed when trying to parse attached action stats.
I fixed it in the code and wrote a test for it. If you want to reproduce, just run the test on a repository that hasn't got the fix yet.
=> Fix tc u32 action stats

pyroute2/__init__.py
Hello,
This adds a `logging.NullHandler` handler to the library's top-level logger, as recommended by [the official Python documentation](https://docs.python.org/2/howto/logging.html#library-config) for libraries.
This fixes an issue that had no satisfactory solution until now:
- We either add a regular log handler, which should not be done in a library as it can cause duplicate logs (issue #255)
- Or we don't, but this produces warnings on logging calls when no handler has been configured by the library user (issue #270)
This is not compatible with Python 2.6 but I can amend the pull request if necessary.
=> logging: fix spurious warnings when no logging handler is configured

pyroute2/netlink/rtnl/tcmsg/act_connmark.py, pyroute2/netlink/rtnl/tcmsg/common_act.py, tests/general/test_tc.py
Hello,
I added the tc connmark action + a test for it.
I wasn't quite sure about the proper way to handle the padding in `TCA_CONNMARK_PARMS`, this looks fine to me but tell me if there's a better way. 
As for the test, this is a quite recent addition to the kernel as far as I know, so I wrapped it in a `skip_if_not_supported`.
=> add the tc connmark action

pyroute2/netlink/rtnl/tcmsg/act_mirred.py, pyroute2/netlink/rtnl/tcmsg/common.py, tests/general/test_tc.py
This fixes an oversight in the mirred action: I forgot to properly set the action type which led to unexpected behavior such as duplicate packets in redirect mode.
I added a few action types to `pyroute2.netlink.rtnl.tcmsg.common.tc_actions` as well because there was a missing action I needed.
=> Tc mirred action fix

pyroute2/netlink/__init__.py, pyroute2/netlink/rtnl/ndmsg.py, pyroute2/netlink/rtnl/ndtmsg.py, pyroute2/netlink/rtnl/req.py, pyroute2/netlink/rtnl/rtmsg.py, pyroute2/netlink/rtnl/tcmsg/common.py
This patch reduce memory consumption for some workloads like reading neighbours on hosts with big NDP tables (~10k entries):
```
import socket
IPRoute().get_neighbours(socket.AF_INET6)
```
Peak memory usage descreased from 70MB to 30MB, see https://gist.github.com/blackwithwhite666/971bf9a9f8ff1905be5c4cc15decb5b2 for details.
Another important change (and this may change API provided by nlmsg_base): parent is weakref by default. Because of it no reference cycles created so there is no need to track those objects by GC (see graphs from previous link).
jfyi: some tests fails on master branch for me, https://gist.github.com/blackwithwhite666/3d6d6ecd8678c3db05b5c487f1b9315c, i don't find what's the problem with them.
=> Try to reduce memory usage in case of messages containing lots of similiar entries

pyroute2/iproute.py
Note that I am a bit puzzled that the flags are not the same than for `tc`, but this works. In `tc/qdisc.c`, there is:
```c
if (matches(*argv, "add") == 0)
return tc_qdisc_modify(RTM_NEWQDISC, NLM_F_EXCL|NLM_F_CREATE, argc-1, argv+1);
if (matches(*argv, "change") == 0)
return tc_qdisc_modify(RTM_NEWQDISC, 0, argc-1, argv+1);
if (matches(*argv, "replace") == 0)
return tc_qdisc_modify(RTM_NEWQDISC, NLM_F_CREATE|NLM_F_REPLACE, argc-1, argv+1);
```
=> tc: allow to change or replace a qdisc

pyroute2/netlink/rtnl/req.py
Fixes #374
Looking at the code, this looks like what's missing, but I haven't had a chance to test it yet. I can't do it currently as you can't make mavlans on tunnel interfaces and I'm currently on a VPN to work and on a laptop.
But this is breaking production stuff for me, so I think I'm just going to have to hot patch it and get back to you 😉
=> Add check for macvlan in set_specific

pyroute2/config/__init__.py, pyroute2/netlink/rtnl/ifinfmsg/__init__.py
In order to allow for things like Pyinstaller, it is best to use a more
standard approach to plugin support.
Signed-off-by: Antoni Segura Puimedon <antonisp@celebdor.com>
=> use stdlib for plugins

pyroute2/netlink/rtnl/ifinfmsg/__init__.py
Eliminate unnecessary chdir() and only do sys.path.append() once.
Signed-off-by: Eugene Crosser <crosser@average.org>
=> plugins: Minor cleanup of plugin loading code

pyroute2/netns/__init__.py
With default value 308, power systems fails to create NetNS object. This patch fixes it with proper value for ppc64* arch.
Signed-off-by: Harish <harish@linux.vnet.ibm.com>
=> netns: ppc64 arch reference fixed

pyroute2/ipdb/interfaces.py
In issue https://github.com/svinota/pyroute2/issues/361 the example file qinq.zip works with IPRoute.
When trying the same with IPDB, parsing the result when committing an interface with vlan_protocol fails:
```
File "qinq.py", line 9, in <module>
ipdb.create(kind="vlan", ifname="qtest.50", link=hidx, vlan_id=50, vlan_protocol=0x88a8).commit()
File "/usr/local/lib/python2.7/dist-packages/pyroute2/pyroute2/ipdb/interfaces.py", line 1060, in commit
raise error
pyroute2.ipdb.exceptions.CommitException: target vlan_protocol is not set
```
This fixes the issue for me.
This is the modified qinq.py:
```python
from pyroute2 import IPDB
ipdb = IPDB()
ipdb.create(kind="dummy", ifname="qtest").commit()
hidx = ipdb.interfaces['qtest']
ipdb.create(kind="vlan", …
```
=> Correctly parse IFLA_VLAN_PROTOCOL in IPDB interface

pyroute2/ipdb/main.py
In `register_callback()` check if `mode` is one of 'pre' or 'post'
and raise exception if it is not, the same way as it is already done
in `unregister_callback()`.
Signed-off-by: Eugene Crosser <crosser@average.org>
=> IPDB: register_callback: check if `mode` is valid

pyroute2/ipdb/interfaces.py
I found an issue in https://github.com/svinota/pyroute2/blob/master/pyroute2/ipdb/interfaces.py#L1240 which causes following:
```
Exception in thread IPDB event loop:
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/lib/python2.7/site-packages/pyroute2/ipdb/main.py", line 1252, in serve_forever
func(msg)
File "/usr/lib/python2.7/site-packages/pyroute2/ipdb/interfaces.py", line 1244, in _new
del self.neighbours[old_index]
File "/usr/lib/python2.7/site-packages/pyroute2/common.py", line 202, in __getattribute__
raise e
AttributeError: 'InterfacesDict' object has no attribute 'neighbours'
```
=> ipdb.interfaces: Fix AttributeError

pyroute2/netlink/rtnl/tcmsg/act_vlan.py, pyroute2/netlink/rtnl/tcmsg/common_act.py
This adds support for the TC Vlan Action. The parameters for the python tc function are : 
- *v_action* : can be "push", "pop" or "modify"
- *id* : vlan id, integer (can be hexadecimal)
- *protocol* : can be either "802.1Q" or "802.1ad" . Those values reflect the configuration option of the tc-vlan man page
- *priority* : PCP value
The *v_action* is required, and the vlan *id* is required for "push" and "modify" actions. The protocol defaults to "802.1Q", and the priority to 0 (if unspecified).
=> Adding support for the TC Vlan action

pyroute2/ipdb/main.py, pyroute2/ipdb/routes.py
This solves three problems:
1. If the 'tos' field on an existing IPv4 route is changed using pyroute2, then pyroute2 currently adds a new route and fails to remove the old route.  This is fixed by adding the 'tos' to the RouteKey when appropriate (for IPv4 but not IPv6).
2. If the 'scope' or 'oif' field on an existing route is changed, then pyroute2 unnecessarily removes and re-adds the route, causing a brief outage.  This is fixed by removing these fields from the RouteKey so that the route will be updated in-place.
3. If the 'priority' field on an existing route is changed, then pyroute2 removes the old route before adding the new route, causing a brief outage.  This is fixed by adjusting the order of operations so that the new route is added before the old route is removed.
=> ipdb: match RouteKey to kernel and improve route change handling on key change

docs/index.rst, docs/wiset.rst, pyroute2/wiset.py, tests/general/test_wiset.py
IPSet object from ipset.py is providing a low level API to manage
NFNetlink sockets. It's "stateless" since it does not have any context
of the ipset manipulated (for example, to know ipset entries and help to
parse responses). Moreover, it's made to manipulate all ipsets in the
same time.
This module provides or more high level API, based on WiSet object. A
WiSet is directly mapped to a real ipset object in kernel, and help to
store metadata like:
- type of entries
- configuration of ipset (counters enabled, comments, etc)
- low level configuration like hash table size, module revision, etc
All data are stored in native python format, and you don't need to know
IPSET_ATTR_* variable to set or read values. Netlink interface is fully
abstract with this object.
It's help to run a batch of …
=> Add new wiset module

pyroute2/netlink/rtnl/ifinfmsg/plugins/vti6.py
initial vti6 commit used wrong field order
=> fix NLAs for vti6 device

pyroute2/netlink/nlsocket.py, tests/general/test_ipr.py
Hello,
I noticed IPRoute contexts could still be used after being closed in Python 2. I assume I'm not the first one to stumble upon this, but it has caused inconsistent behavior between Python versions in our codebase so I figured it warranted a fix.
The gist of the issue is that `NetlinkSocket` stores references to the underlying socket methods, which can change (and do). So instead of storing references I used `__getattr__` to always return the "current" methods.
The reference-based approach caused IPRoute sockets to be in an inconsistent state when closed:
- the socket methods are replaced by dummies at closing time
- the stored reference still points to the old method
- the underlying os-level socket is not necessarily closed
Thus data still could be sent over the socket even if it …
=> Fix for IPRoute objects that can still be used after close in Python 2

pyroute2/ipset.py
Default limit on list:set is 8, this change will allow a user to set a different size limit on list:sets
=> Allow for size limits on list:set to be configurable

pyroute2/ipdb/main.py
This substitutes it with a weak reference as suggested by fangzhen.
This commit fixes #430
Signed-off-by: Antoni Segura Puimedon <antonisp@celebdor.com>
=> Do not make atexit register hold ref to all ipdbs

pyroute2/netns/__init__.py
Confirmed as working after switching code to 375 (though if that hadn't worked, I'd have been lost).
```
>>> platform.uname()
uname_result(system='Linux', node='localhost', release='4.4.86-11979-g09b49365a3c4', version='#1 SMP PREEMPT Mon Jan 8 23:12:27 PST 2018', machine='aarch64', processor='ARMv8 Processor rev 4 (v8l)')
>>> platform.machine()
'aarch64'
>>> platform.architecture()
('32bit', '')
```
ChromeOS Version 63.0.3239.140 (Official Build) (32-bit), released January 2018.
=> added 32 bit aarch64 variant, found on chromebook plus

pyroute2/ipset.py, pyroute2/netlink/nfnetlink/ipset.py, tests/general/test_ipset.py
Hi,
This PR adds support for the `skbinfo` capability into the `ipset` which includes setting `skbmark`, `skbprio`, and `skbqueue` at adding entry.
Thanks.
=> ipset: add skbinfo capability

pyroute2/netlink/__init__.py, pyroute2/netlink/diag/__init__.py, ss_tst.py
**Clarificiation ONLY PR** for why plain NLA extension to nlmsg is not enough in order to parse sk specific data although implemented this way in other NL interactions. Excuses for this hideous form of communicating this. Example here based on UNIX sks.
The data blob is definitly there, visible when introspecting. NLA's are not ending up in the attrs, though.
@svinota  Did a little deep dive into the nla_map compilation. Was this ever working? Would be striking if not, since heavily used this way. (see my tst script)  Seems all yours. Could you have look?
=> dummy: Clarifyciation for TCP ss prep

pyroute2/netlink/rtnl/ifinfmsg/compat.py, pyroute2/netlink/rtnl/ifinfmsg/proxy.py, pyroute2/netns/__init__.py
We need s390 support for creating network namespaces via pyroute2. Since OpenStack is exploiting pyroute2 [1], Neutron is broken on s390.
Would it be possible to trigger a release after this got merged? Thanks!
[1] openstack/neutron@c4d4336
=> Add s390x support

pyroute2/netns/nslink.py
There's no flag named O_EXIST. It should be O_EXCL that ensures the call
fails if the namespace already exists.
=> Fix the file creation flag O_EXCL

pyroute2/netlink/nfnetlink/conntrack.py
Hi,
This PR adds getter for the cpu statistics into the conntrack.
It returns a list of dictionaries which contains the same values as command output of `conntrack -S`.
Thanks.
=> conntrack: add getter for cpu statistics

pyroute2/netlink/nfnetlink/__init__.py
The convention in nfnetlink is to use network byte order in every header field
except for old nft implementation on the ancient kernel.  Also recent kernel
provided a workaround for old nft, so now en/decoding res_id field as network
byte order seems safe:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a9de9777d613500b089a7416f936bf3ae5f070d2
=> nfnetlink: fix byte order of nfgen_msg.res_id field

pyroute2/netlink/nfnetlink/nfctsocket.py
Hi,
This PR adds support for conntrack entry deletion.  It provides pure mapping for kernel API.
If the delete function by "search and destroy" like conntrack command is needed, I believe conntrack module should provide it.
Thanks.
=> nfctsocket: add support for entry deletion

cli/ss2.py
ss2 shall become the classic ss cli pendant for pyroute2, following the
tradition of having cli mechanisms integrated with the according core
kernel integration components.
This commit introduces a crude yet working ss2 skeleton - supporting TCP only at first.
=> sock_diag: shaping cli ecolosis of traditional ss

pyroute2/ipdb/main.py, pyroute2/netlink/nlsocket.py, pyroute2/netlink/rtnl/iprsocket.py
Please consider this proposal.
In mass network topology updates, thousands of netlink packets lead to excessive resource usage (one thread per event use much memory and results in slow processing) and hanging process (recovery from failed IPDB commit is slow, and monitoring thread is prone to die without the master thread noticing).
This change allows the user to process incoming netlink messages in an event loop (in the main thread, or in any user-initiated thread(s)), and netlink socket receive errors are passed via the same queue, and re-raised in the master thread. This allows the user program to notice that netlink events where lost and take appropriate action.
The last commit of three allows to specify the size of netlink socket send and receive buffers, and thus control the "storm …
=> Introduce "eventloop" style API to better handle netlink event storms

pyroute2/iwutil.py, pyroute2/netlink/nl80211/__init__.py
The `ssids` parameter has been added to the `scan()` method. This allows to perform active scanning when a list of SSIDs is provided.
=> Allow to perform active scanning.

pyroute2/iwutil.py, pyroute2/netlink/nl80211/__init__.py
Add a `flush_cache` parameter to the `scan()` method, in order to flush the cache before scanning.
=> Allow to flush the cache before scanning.

pyroute2/netlink/nl80211/__init__.py
In `elementsBinary::decode()` method, decode the RSN IE. Store vendor specific IEs in a list, since there may be more than only one.
=> Decode the RSN IE, and store vendor specific IEs in a list.

pyroute2/netlink/__init__.py
This PR adds missing types in `pyroute2/netlink/__init__.py`.
These are required in the code added in PR #514
=> Missing types (int8, int16, and int64) have been added.

pyroute2/netlink/rtnl/tcmsg/common.py
/**
* struct gnet_stats_basic - byte/packet throughput statistics
* @bytes: number of seen bytes
* @packets: number of seen packets
*/
struct gnet_stats_basic {
__u64   bytes;
__u32   packets;
};
=> tc: fix size of packets

pyroute2/netlink/rtnl/rtmsg.py
Tunnelled/encapped mpls labels can also have a TTL attribute
passed with them. This was getting marked as unknown since it
didn't know how to parse it. Added the proper mapping.
=> rtmsg: Add mapping for ttl attribute in tunnelled mpls label

pyroute2/netns/__init__.py, tests/utils.py
While glibc is currently at version 6, there are other libc projects in
use which implement an older interface version, such as uClibc. Instead
of explicitly specifying the libc name, search for any libc that is
available.
=> Don't assume libc version

README.md, pyroute2/netlink/rtnl/req.py, pyroute2/netlink/rtnl/rtmsg.py
Changes:
- Fix bug in seg6 decode(): flush_routes() give an error when it tried to delete all the routes because encapmode field was not decoded
- Introduces IPRoute support for seg6local tunnel
- Adds behaviours: End, End.X, End.T, End.DX2, End.DX6, End.DX4, End.DT6, End.B6, End.B6.Encaps
- Supports hmac functionality for SRH
- Initial parsing of human friendly form
=> Fix bug in seg6 encap decode(), add seg6local support

pyroute2/ipset.py
Ipset protocol version is usually six (version six was released in
2011), so it was hardcoded since the beginning in IPSet class.
However, a new version is available since a week:
https://lwn.net/Articles/769839/
This patch does not implement new commands of this version, but allow at
least to detect kernel running with it
=> ipset: add get_proto_version method

pyroute2/netlink/nlsocket.py
This does up to three retries of nlm_request when it fails with error code 16 ("Device or resource busy"), sleeping for 300ms between attempts.
This error seems to happen when multiple requests happen in quick succession, so slowing things down slightly when it happens seems to work.  I haven't spent any time experimenting with shorter sleeps - shorter times may also work or may work less reliably.
=> Add retries of failed nlm_request calls for error code 16

pyroute2/netlink/rtnl/rtmsg.py
Replace Python2 dict.iteritems() with Py2/Py3 dict.items(),
to avoid Python3 errors.
=> Replace "iteritems" with "items"

pyroute2/nftables/expressions.py
Stops the following code from raising a TypeError in Python3.
Retains compatibility with Python2.
```
from pyroute2.nftables import expressions
expressions.ipv4addr(src='172.16.1.0/24')
```
=> Replace strings with bytestrings to support Python3.

pyroute2/netns/nslink.py, pyroute2/remote/__init__.py
This patch changes the way of stopping the NetNS server, by sending
a SIGTERM signal and waiting for the server loop to finish. When the
signal is received, the loop control flag is inverted. Once the loop
is finished, the server process ends.
This patch also modifies the Transport class receiver function loops.
When the Transport object is closed, the receiver loops are stopped but
not the file descriptors. Those file descriptors, created in the NetNS
parent class, are closed at the end of the NetNS.close function, once
the child process (Server) is finished and the Transport receiver loops
are stopped. At this point, the file descriptors are not in use and can
be closed.
=> Stop NetNS server gracefully

pyroute2/iproute/linux.py, tests/general/test_ipr.py
NOARP is only a flag, that one can set with sysfs (with
/sys/class/net/<dev>/flags file) or using interface flag with netlink.
This commit adds a helper to mimic ip commands:
* ip link set arp on dev <dev>
* ip link set arp off dev <dev>
It's now possible to do:
ip.link('set', arp=True, index=ifindex)
ip.link('set', arp=False, index=ifindex)
=> iproute: add support of NOARP flag

pyroute2/ipdb/main.py, pyroute2/netlink/rtnl/ifinfmsg/__init__.py, pyroute2/netlink/rtnl/ifinfmsg/plugins/xfrm.py, tests/general/test_ipr.py
Virtual XFRM interfaces are available in Kernel 4.19+
Signed-off-by: Matt Ellison <matt@arroyo.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/svinota/pyroute2/572)
=> rtnl: Add Support for XFRM Interfaces

pyroute2/netlink/rtnl/tcmsg/cls_fw.py
When using the following command, it automatically sets the ethernet protocol to 'all':
`tc filter add dev ifb0 handle 25 fw classid 1:12`
> root@pc-dev:~# tc filter show dev ifb0
> filter parent 1: protocol all pref 49150 fw 
> filter parent 1: protocol all pref 49150 fw handle 0x19 classid 1:12
This patch permits to call tc from pyroute2 and create a tc-fw filter without specifying the protocol to use.
=> cls_fw: set default protocol to ETH_P_ALL when not specified

pyroute2/protocols/rawsocket.py
Otherwise, you can recv packets that you don't expect.
=> Clear packets in raw socket buffer after bind()'ing to an interface or prior to attaching a filter

pyroute2/dhcp/__init__.py
Decoding option 61 was triggering exceptions due to incorrect parsing.
=> fix parsing of options without policy

pyroute2/netns/__init__.py
Hello,
I didn't find any reference in the documentation for this annoying thing. There is perhaps a better way, but in all cases I think that it's a good idea to add documentation on it.
=> netns: add documentation on how to go back on default netns

pyroute2/wiset.py, tests/general/test_wiset.py
Hello,
This pull request add the support of kwargs list for the replace_entries method of wiset in addition to a basestring list.
This allow to use this "atomic" operation to replace the content of an ipset having skbinfo or comments
I also added a test for it.
Best regards
Charles
=> Wiset replace update

pyroute2/netns/__init__.py, tests/general/test_netns.py
Add function to get netns name associated to a PID if it exists.
=> NetNS: get netns name by PID

pyroute2/iproute/linux.py, pyroute2/netlink/rtnl/ifinfmsg/__init__.py, pyroute2/netlink/rtnl/ifinfmsg/plugins/ipoib.py
- Add ipoib nla to allow creation/query of ipoib interfaces
with the defined attributes.
- Document ipoib usage in iproute.linux.RTNL_API.link() docstring.
=> Add support for IPoIB interface

cli/ss2
E.g. glitching for:
sconn(fd=-1, family=<AddressFamily.AF_UNIX: 1>, type=1, laddr='/run/systemd/private', raddr='', status='NONE', pid=None)
With:
[...]
"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pyroute2-0.5.6-py3.7.egg/EGG-INFO/scripts/ss2",
line 114, in _enter_item sk_inode = int(self._parse_inode(flow))
File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pyroute2-0.5.6-py3.7.egg/EGG-INFO/scripts/ss2",
line 64, in _parse_inode sk_path = self._proc_sk_fd_cast % (sconn.pid, sconn.fd) TypeError: %d %format: %a %number %is %required,
%not NoneType
=> ss2: curing nonetype pid

pyroute2/netlink/rtnl/ifinfmsg/__init__.py
This patch adds the abbility to configure infiniband port GUID
and node GUID by implementing classes `ib_port_guid` and `ib_node_guid`
in class IFLA_VF_INFO for serializing and deserializing GUID.
=> Set infiniband port and node GUID

pyroute2/netns/nslink.py
With the change in the behavior of the Transport object, we now need to
close the file_obj associated with the Transport object manually.
Closes #623
=> NetNS: fix the FD leakage

pyroute2/nftables/parser/expr.py
This fixes the `from_dict()` and `to_dict()` methods on Python3.
They previously gave the following errors.
```
File "/home/liam/work/pyroute2/pyroute2/nftables/parser/expr.py", line 109, in from_32hex
res = chr(int(val[i:i + 2], 16)) + res
TypeError: can only concatenate str (not "bytes") to str
```
and...
```
File "/home/liam/work/pyroute2/pyroute2/nftables/parser/expr.py", line 130, in to_32hex
res += format(ord(c), '02x')[::-1]
TypeError: ord() expected string of length 1, but int found
```
=> Change 32hex conversion functions to support both py2 and py3.

pyroute2/iproute/linux.py
iproute2 supports `ip route append ...` command, that allows, possibly
among other things, to set up IPv6 multipath 'device only' routes that
cannot be confitured via the kernel "multipath" interface. Relevant code
in the iproute2 source in ip/iproute.c:2295 looks like this:
if (matches(*argv, "append") == 0)
return iproute_modify(RTM_NEWROUTE, NLM_F_CREATE|NLM_F_APPEND,
argc-1, argv+1);
This commit aims to replicate this functionality in pyroute2.
Signed-off-by: Eugene Crosser <evgenii.cherkashin@cloud.ionos.com>
=> Add support route('append', ...) operation

pyroute2/netns/__init__.py
When ip netns {add|delete} is first run, it bind-mounts /var/run/netns
on top of itself, then marks it as shared. However, if there are already
bind-mounts in the directory from other tools, these would not be
propagated. Fix this by recursively bind-mounting.
Related Patch: https://patchwork.ozlabs.org/patch/796300/
Issue: 640
=> Create namespace recursively bind-mounting

pyroute2/netlink/rtnl/tcmsg/sched_cake.py
This commit allows to get stats from a cake filter including stats per tin.
=> cake: add stats_app decoder

tests/general/test_wireguard.py
This extends the simple wireguard test to check that, as well as the peer existing, the endpoint address has been set.
=> Test: Check wireguard sets endpoint address properly

pyroute2/netlink/__init__.py, pyroute2/netlink/generic/wireguard.py
In order to simplify the code the nla arrays encoding has been fixed using nla_flags for array members as well.
=> wireguard: use nla arrays

pyroute2/netlink/rtnl/tcmsg/cls_basic.py, pyroute2/netlink/rtnl/tcmsg/common_ematch.py
This patch adds support to create multiple matches using basic filter and combine different kinds of ematch.
Documentation was also updated to fit with these new version of the code.
=> tc/basic: add multimatch support

pyroute2/wiset.py, tests/general/test_wiset.py
On "old" kernels, like version 4.19, the kernel does not return any
message for an invalid ipset name:
In [2]: load_ipset("doesnotexists")
In [3]:
However, on recent kernel, we now receive an error. It's probably a good
thing, but it breaks our code compatibility here. So we know catch the
exception to keep consistent behaviour between kernel versions
=> wiset: do not raise exception on recent kernels

pyroute2/ndb/main.py
- Fixes a `SysLogHandler` call.
- Makes loglevel modifiable.
- Prevents reformatting of external logging handlers.
=> Fix and improve NDB logging

pyroute2/conntrack.py, pyroute2/netlink/nfnetlink/nfctsocket.py, tests/general/test_conntrack.py
Hello,
Conntrack().dump_entries() return a lot of objects, and is consuming huge memory (on our tests, more than 200Mo for 17000 entries, for example).
Thanks to nlm_generator now by default to True (side note : more documentation on this configuration could be great!) our script to dump and filter conntrack entries consumes less than 50Mo.
It has less performance impacts, but we also adds some __slots__ definitions on Conntrack related objects.
Conntrack() class is still compatible with nlm_generator sets on False.
=> Enable generator on Conntrack() and reduce memory usage

pyroute2/conntrack.py
Hello, this super() must be deleted because if you want override dump() in a subclass you can't with it
=> conntrack: Remove useless super() on Conntrack

pyroute2/iproute/linux.py, tests/general/test_ipr.py
addr method only accepts 'add', 'delete' and 'dump' commands.
This commit adds 'replace' and a test.
=> Add support for 'replace' command in addr method

pyroute2/netlink/nlsocket.py
This PR does two things.
1. First it fixes the `address not allocated` error described in #562 
2. It changes the `print` for the retry error to a `log.warning`.
While I don't quite understand why the `address not allocated` error does not always happen when the request is retried, this fixes the problem.
=> Fix double free of msg_seq in nlm_request

pyroute2/__init__.py, pyroute2/netlink/generic/l2tp.py, tests/general/test_l2tp.py
This adds support for managing L2TP tunnels in pyroute2. The code
closely mirrors the kernel and iproute2 sources and implements all
available attributes to date.
Tests for the basic operations have been added as well.
Signed-off-by: Felix Kaechele <felix@kaechele.ca>
=> generic: add L2TP support

pyroute2/iproute/linux.py, tests/general/test_ipr.py
This feature has been added in kernel recently (end of 2018), and is now
in iproute2 as well
=> linux: add support of ip neigh get

pyroute2/iproute/linux.py, tests/general/test_ipr.py
Use set intersection to check if index nor ifname is in kwargs. And add
a trivial test for this
Bug-Url: https://github.com/svinota/pyroute2/issues/724
Related-To: https://github.com/svinota/pyroute2/issues/712
=> iproute: fix link_lookup when index/ifname is not set

pyroute2/nftables/main.py
This PR adds the missing hooks for the `ip` family. It also adds support for custom integer priorities.
=> nftables: add missing hooks for the ip family and support custom priorities

pyroute2/wiset.py
Hello,
This commit permit to format the key of the WiSet().content with attributes of port like:
{'1.2.3.4/32,tcp:60005': IPStats(...) ...
It add "tcp:60005" in the key
=> wiset: Adding 'port' attribute for key of WiSet().content

pyroute2/netlink/__init__.py, pyroute2/netlink/nfnetlink/nftsocket.py
Base chain priority can be negative (see https://wiki.nftables.org/wiki-nftables/index.php/Configuring_chains). However, since an unsigned value is used, an exception will be thrown when the struct module attempts to pack a negative value that is passed to `NFTables.rule` as the priority parameter. Thus, ff0f00cb309464fa2b406a70ec05abd42f27c0a8 adds signed big endian values.
0c78cd03991786465fe0b01b32a325acea9bf613 fixes a typo.
=> nftables: Allow negative hook priority and fix typo

docs/index.rst, docs/nftables.rst, examples/nftables.py
- Add nftables docs to be generated
- Add a very simple example showing pulling from inet table
I was unable to get docs to build. Even before I made any changes. Maybe to help add CI + get building again unless I was causing the issue. README.md says use `make docs` but that's not a valid sphinx command. Do I need an older version?
```
(ip) cooper@home1:~/repos/pyroute2/docs$ make docs
make: *** No rule to make target 'docs'.  Stop.
```
Error with `make html`: https://pastebin.com/bM4jkvMk
Fixes  #747
=> Add nftables docs + simple example

pyroute2/iproute/linux.py
Hello,
It's not a huge improvement, but we just catched it we doing some performance profiling
=> linux/neigh: do not run _match when match is an empty dict

pyroute2/common.py
Increase the DEFAULT_RCVBUF size from 16K to 32K to allow more data
to be passed along with newer kernels.
Fixes #751
Signed-off-by: Billy Olsen <billy.olsen@gmail.com>
=> Increase DEFAULT_RCVBUF size for newer kernels

pyroute2/netlink/diag/__init__.py
There were some symbols from `struct tcp_info` missing (c.f. `include/uapi/linux/tcp.h`). Those were added now.
=> fixed missing tcp diag info symbols

pyroute2/netlink/rtnl/req.py, pyroute2/netlink/rtnl/rtmsg.py
I want to use End.BPF seg6local function with pyroute2.
I saw modified version of https://github.com/Zashas/pyroute2/commit/6fa211a87375dc31bfacedbcb676047a66833c02.  It is partially merged in master of pyroute2, but partially not.
To use End.BPF with `fd` and `name`, I changed some code by refering modified version.
Here is use case of `End.BPF`:
```python3
from bcc import BPF
b = BPF(src_file="source.c")
fn = b.load_func("pass", 19)
ipr = IPRoute()
idx = ipr.link_lookup(ifname=iface)[0]
sid = 'fd00::1/128'
encap = {'type':'seg6local', 'action':'End.BPF', 'bpf':{'fd':fn.fd, 'name':fn.name}}
ipr.route("add", dst=sid, oif=idx, encap=encap)
```
source.c:
```source.c
#include <linux/bpf.h>
int pass(struct __sk_buff *skb) {
return BPF_OK; // packet continues
}
```
=> Add End.BPF to seg6local

pyroute2/ipdb/routes.py
Hi,
I want to use the End.BPF seg6local endpoint; @kyontan already discussed that in his pull request 1d73ed4595529b3d80199aaa80dfa4b46bfdc414.
However, if the `encap` was not MPLS, the code crashed because we try to iterate over a `None` object. the current try-catch does not handle that, as the `get_attr` returns a default valu and does not raise an error.
Maybe support for other encapsulations should be added, but it works like this for the End.BPF now.
=> Ignore other encap_types load_netlink

pyroute2/ndb/main.py
Signed-off-by: Timothée Dzik <timdzik@fb.com>
In the latest 0.5.15 [this line](https://github.com/svinota/pyroute2/blame/master/pyroute2/ndb/main.py#L307) has been included which work on `Python >= 3.6` but not on `Python < 3.6`
Simple fix, change the way to inject the var in the warning.
=> [NDB] Change warning to work with Python < 3.6

cli/ss2
Moving to GPL v2 character of licensing on request
of main maintainer.
=> ss2: align license with overall libary project

pyroute2/netns/process/proxy.py
Intensive usage of pyroute2 over long period of time creates excessive
amount of leftover file descriptors. Those would normally be cleaned at
program exit, but in long running services that is not an option.
To prevent that behavior this patch explicitly closes pipes created with
multiprocessing.popen_fork.Popen._launch when they are no longer needed.
Signed-off-by: Michal Zylowski <michal.zylowski@ovhcloud.com>
Bug-Url: https://github.com/svinota/pyroute2/issues/622
Related to #622
=> Fix file descriptors leak

Makefile
Fixed #783
When trying to install this on systems the don't have unqualified 'python' (ie no version specified) executable you get an error:
```
/bin/sh: python: command not found
make: *** [Makefile:175: README.md] Error 127
```
My guess is this was a typo and it was intended to use '${python}' for this rule instead, so I fixed it.
=> Fixed "python" in for make README.md rule

pyroute2.core/pr2modules/netlink/nl80211/__init__.py
This fixes #555 to some extent. I haven't seen `NL80211_BAND_ATTR_IFTYPE_DATA` in the wild, but other information looks fine. Frequencies are easily accessible, and I think most people really interested only in this one. Maybe we should also parse capabilities and present them as individual flags, but I'm not quite sure how to do this in a manner that will fit everybody, so I left them as uints for now.
I don't have much experience with Python's struct format strings, so I left C structure definitions for review.
=> nl80211: parse wiphy bands

pyroute2.core/pr2modules/netlink/generic/wireguard.py
Load the keys from the correct place in the message, and load them as the right length as well. Fixes #803.
=> wireguard: fix parsing keys

pyroute2.core/pr2modules/common.py
Increase the DEFAULT_RCVBUF size from 32K to 64K to allow more data
to be passed along with newer kernels.
Fixes #813
=> Increase DEFAULT_RCVBUF size to support 127 VFs

pyroute2.ipset/pr2modules/wiset.py
The [`update_dict_content`](https://github.com/svinota/pyroute2/blob/29e15d854b75653cd1400cbbac230dd5298648ac/pyroute2.ipset/pr2modules/wiset.py#L233-L253) method does currently not handle `mac` types. This create wrong results when calling `wiset.load_ipset('..').content` since all entries are mapped to a empty key (if using an `hash:mac` ipset).
=> ipset: add missing mac support for ipset content

pyroute2.core/pr2modules/netlink/rtnl/req.py
```
...
File "/nix/store/jqlhx84p232pja1bcwdc3higlwj7f0fp-python3.9-pyroute2-core-0.6.4/lib/python3.9/site-packages/pr2modules/iproute/linux.py", line 1969, in route
ret = self.nlm_request(msg,
File "/nix/store/jqlhx84p232pja1bcwdc3higlwj7f0fp-python3.9-pyroute2-core-0.6.4/lib/python3.9/site-packages/pr2modules/netlink/nlsocket.py", line 391, in nlm_request
return tuple(self._genlm_request(*argv, **kwarg))
File "/nix/store/jqlhx84p232pja1bcwdc3higlwj7f0fp-python3.9-pyroute2-core-0.6.4/lib/python3.9/site-packages/pr2modules/netlink/nlsocket.py", line 881, in nlm_request
self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
File "/nix/store/jqlhx84p232pja1bcwdc3higlwj7f0fp-python3.9-pyroute2-core-0.6.4/lib/python3.9/site-packages/pr2modules/netlink/nlsocket.p …
```
=> [core] Fix BPF encap handling in IPRouteRequest filter

pyroute2.core/pr2modules/iproute/linux.py, pyroute2.nslink/pr2modules/nslink/nslink.py
File descriptors are not shared between parent and child after `fork()`.
Therefore, calls to `os.open()`/`os.close()` must be proxied.
See #826.
=> [core, nslink] Open/close files in child process

pyroute2.ndb/pr2modules/ndb/source.py
This is so that they can be re-added later with the same name.
=> [ndb] Delete NDB sources from table on finalize

pyroute2.core/pr2modules/iproute/linux.py, pyroute2.ndb/pr2modules/ndb/objects/interface.py, pyroute2.nslink/pr2modules/nslink/nslink.py
Addresses the issue discussed in #839.
=> [core, ndb, nslink] Use different approach for is_peer()

docs/conf.py
Pyroute2 conf.py is still using app.add_stylesheet() which was deprecated in
the favor of app.add_css_file(). In 4.x, app.add_stylesheet() was completely
removed, rendering Pyroute2's doc incompatible with Sphinx 4.x This patch
fixes it.
=> Fix compat with Sphinx 4.x

pyroute2.core/pr2modules/conntrack.py, pyroute2.core/pr2modules/netlink/nfnetlink/nfctsocket.py
Hello,
Sorry for the lag, we developed this feature two years ago but we never use it before today.
So, this is an implementation for kernel side filtering (again !) on conntracks. As you may imagine, performance boost is huge on routers with large number of conntracks.
Sadly, we introduced a bug in kernel so tuple_reply is not working as excepted. But that should be fixed soon
=> Conntrack kernel side filtering

pyroute2.core/pr2modules/iproute/linux.py, pyroute2.core/pr2modules/netlink/rtnl/req.py, pyroute2.core/pr2modules/netlink/rtnl/rtmsg.py
This PR adds the support for the _SRv6 End.DT4 behavior_.
The SRv6 End.DT4 behavior is used to implement IPv4 L3VPN use-cases in multi-tenants environments. It decapsulates the received packets and performs IPv4 routing lookup in the routing table of the tenant.
The SRv6 End.DT4 behavior has been introduced in the Linux kernel in the commit [1] and it is available since kernel version 4.11.
The _iproute2_ suite has been extended as well for supporting the SRv6 End.DT4 behavior [2].
An example iproute2 command to instantiate an SRv6 End.DT4 behavior is the following:
`$ ip route add 2001:db8::1 encap seg6local action End.DT4 vrftable 100 dev eth0`
In the above command, the `vrftable` attribute indicates the routing table associated with the VRF device used by SRv6 End.DT4 for routing IPv4 …
=> Add support for the SRv6 End.DT4 behavior

pyroute2.core/pr2modules/netlink/rtnl/ifinfmsg/__init__.py
Updated `IFLA_BRPORT_*` enums based on Linux kernel 5.10.76
I would only like to use `IFLA_BRPORT_NEIGH_SUPPRESS` but I thought the others might be useful for somebody.
=> Update IFLA_BRPORT_* enums

pyroute2.core/pr2modules/iproute/linux.py, pyroute2.core/pr2modules/netlink/rtnl/ifinfmsg/__init__.py, pyroute2.core/pr2modules/netlink/rtnl/req.py
- Fixed `brport` command via `NetNS`
The issue was caused by using `IPBrPortRequest` directly and not just as an attribute filter. When the netns server tried to reconstruct the `IPBrPortRequest` object the `allowed` property did not exist yet
Fixes #864 
- Added `IPRoute.link` initial slave support
iproute2 can set slave options like this:
`ip link set dev <devname> type <type>_slave <options...>`
Since IPRoute.link command already handles `IFLA_INFO_DATA` creation it was easier to modify it to support `IFLA_INFO_SLAVE_DATA` too. For this to work `ifinfmsg` must have been updated to handle slave options (currently only `bridge_slave`)
- Rewritten `IPRoute.brport('set', ...)` to use `IPRoute.link('set', kind='bridge_slave', ...)`
Since `IPRoute.link` is now capable to handle slave options …
=> Fixed NetNS.brport and brport('set')

pyroute2.nslink/pr2modules/nslink/nspopen.py
Fix for the issue that NSPopen's release() occasionally crashes
with an OSError / "Bad File Descriptor" inside
self.channel_out._writer.close().
To still avoid the file descriptor leak in multiprocessing.Queue
but be more robust: Switch from closing the writer explicity to
deleting the Queue object.
Fixes #871
=> Fix occasional crashes in NSPopen.release

pyroute2.ipdb/pr2modules/ipdb/interfaces.py
On Point to Point connections like PPPoE the local ip address
is in IFA_LOCAL and not in IFA_ADDRESS.
IFA_ADDRESS is the remote ip address in that case.
Check for IFA_LOCAL first before using IFA_ADDRESS.
Signed-Off-By: Sven Auhagen <sven.auhagen@voleatech.de>
=> IPDB: Interface Address AF_INET6

pyroute2.core/pr2modules/netlink/__init__.py
[`nlmsg_base.setvalue`][1] overwrites the header if the value is a dict, and all classes derived from `nla` are such dicts.
[`nlmsg_base.encode`][2] first sets nested header type to the index for array entries; the following call to `setvalue` will remove the type, so all entries end up with index 0 (which the kernel won't accept, resulting in `EINVAL`).
[`nlmsg_base.encode_nlas`][3] has the same issue; it first sets sets the header type and then calls `setvalue`, so the encoded NLA will end up having a header type 0 (and the kernel will probably ignore the NLA).
Perhaps `nft` is the only compex enough subsystem to use those features, otherwise I can't see how nobody had issues with this before... (I'm using the low-level types from `pr2modules.netlink.nfnetlin`k to modify nftable sets, …
=> Fix encoding of nested/array NLAs

pyroute2.core/pr2modules/netlink/rtnl/tcmsg/cls_u32.py
`socket.AF_INET` is 2 (at least on Linux) so the resulting filter had `protocols.ETH_P_AX25`specified.
This is incorrect, as the example clearly talks about IP packets. Now the examples from documentation actually work.
=> docs: fix the protocol in the u32 filter example

pyroute2.core/pr2modules/netlink/nfnetlink/nftsocket.py
When decoding nftables rules with ranges (`pprint.pprint(pyroute2.NFTables(nfgen_family=1).get_rules())`), it fails with the following exception:
```
File "/path/to/pyroute2/pyroute2.core/pr2modules/netlink/__init__.py", line 1439, in ft_decode
self.decode_nlas(offset)
File "/path/to/pyroute2/pyroute2.core/pr2modules/netlink/__init__.py", line 1386, in decode_nlas
nla_instance = msg_class(
File "/path/to/pyroute2/pyroute2.core/pr2modules/netlink/__init__.py", line 734, in __init__
self.compile_nla()
File "/path/to/pyroute2/pyroute2.core/pr2modules/netlink/__init__.py", line 1302, in compile_nla
nla_class = getattr(self, nla_class)
AttributeError: 'nft_range' object has no attribute 'nfta_data'
During handling of the above exception, another exception …
```
=> nftables: Fix nftables expressions

pyroute2.core/pr2modules/iproute/linux.py
Flags are not the same between NEW and DELETE request. In file netlink.h
we can see:
/* Modifiers to NEW request */
#define NLM_F_REPLACE   0x100   /* Override existing        */
#define NLM_F_EXCL      0x200   /* Do not touch, if it exists   */
#define NLM_F_CREATE    0x400   /* Create, if it does not exist */
#define NLM_F_APPEND    0x800   /* Add to end of list       */
/* Modifiers to DELETE request */
#define NLM_F_NONREC    0x100   /* Do not delete recursively    */
#define NLM_F_BULK      0x200   /* Delete multiple objects  */
So NLM_F_BULK is the same value than NLM_F_EXCL. NLM_F_BULK has been
added in this kernel commit:
https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=a6cec0bcd34264be8887791594be793b3f12719f
When this flag is set, pyroute now get a …
=> iproute/linux: try to improve flags when sending del messages

pyroute2.core/pr2modules/common.py, pyroute2.core/pr2modules/netlink/nfnetlink/nftsocket.py, pyroute2.core/pr2modules/netlink/nlsocket.py, pyroute2.nftables/pr2modules/nftables/main.py
Hello,
this PR is motivated by the lack of error reporting for nftables write operations. I have seen that there are unfinished classes like `BatchSocket` and `BatchAddrPool`, which are probably supposed to tackle the issue which I am addressing here. So I hope that this PR is not too intrusive or diverging too much from your intention.
Currently, the handling of batch messages is difficult, as `nlm_request` sends each message separately and listens for responses from a single message sequence number only. Therefore, 39741a4660d25cccf59f750dbb354d8c0fc16e0c introduces `nlm_request_batch`, which can be supplied with a list of messages. The function will then listen for expected responses for any of the supplied messages and return/yield them to the caller.
This is leveraged by …
=> nftables: Add more operations and raise kernel errors

pyroute2.core/pr2modules/netlink/rtnl/tcmsg/em_ipset.py
I found a new regression on master. Reproducer code is:
```python
from pyroute2.wiset import WiSet, load_ipset
with WiSet(name="toto-temporary") as wiset:
wiset.create()
ip = IPRoute()
match = [{"kind": "ipset", "index": load_ipset("toto-temporary").index, "mode": "src"}]
ip.tc("add-filter", "basic", 0, parent=0x10000, classid=0x10010, match=match)
with WiSet(name="toto-temporary") as wiset:
wiset.destroy()
```
On master, I get this backtrace:
```
File "/bisect", line 8, in <module>
ip.tc("add-filter", "basic", 0, parent=0x10000, classid=0x10010, match=match)
File "pyroute2_pkg/pr2modules/iproute/linux.py", line 1725, in tc
opts = p.get_parameters(kwarg)
File "pyroute2_pkg/pr2modules/netlink/rtnl/tcmsg/cls_basic.py", line 170, in get_parameters …
```
=> tc/em_ipset: fix a crash on encoding

pyroute2.core/pr2modules/iproute/linux.py
9a891ca02367ad8c1fcb31349a97f32c3f24860b causes flags that do not fit into the `flags` field of `ifaddrmsg` to raise an exception. Therefore, this commit always uses an `IFA_FLAGS` NLA to pass the flags.
```
ip.addr('add', index=index, address=address, prefixlen=prefixlen, flags=IFA_F_NOPREFIXROUTE)
```
iproute2 handles this [similarly](https://github.com/shemminger/iproute2/blob/a17aac1b52d082fe8e4619603fe4022cf2eb9403/ip/ipaddress.c#L2485).
=> iproute: Support flags that do not fit into ifaddrmsg

.github/workflows/pull_request.yml, .github/workflows/push.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

Makefile
Both the `dist` and `uninstall` targets had listed `clean` and `VERSION`
listed as dependencies *before* `setup`.
However, these dependencies need to be performed in this particular
order and `Makefile` dependencies do not guarantee dependency ordering
when executed with more than one job.
As the `clean` and `VERSION` targets are only needed for `setup`, we can
move their execution to be always part of `setup` and then enforce
ordering by explicitly calling them sequentially.
Some discussion on this can be found here:
https://stackoverflow.com/questions/8496135/parallel-makefile-requires-dependency-ordering/8496739#8496739
Additionally this commit replaces the `ls` parsing with `find` and moves
templating listing into a separate method to deduplicate the code.
This obsoletes the need for …
=> add explicit dependency ordering in setup target

pyproject.toml
Fixes: 9714df3404b5 ("setup: remove setup.py")
=> setup: specify "build-backend" in pyproject.toml

pyroute2/requests/rule.py
During the refactoring of the ip rule module, the default action when
adding a rule with a table was incorrectly re-written. Adding a rule
with a table parameter created incorrect rule entries.
Fixes #964
=> Fix default action in RuleIPRouteFilter

pyroute2/netlink/nlsocket.py, pyroute2/netlink/rtnl/iprsocket.py, tests/test_linux/test_ipr/test_compile.py
Netlink sockets to support CompileContext::
with nlsocket.compile():
data = nlsocket.high_level_call()
... now `data` will contain a compiled request, that can be actually sent
to the kernel::
for request in data:
nlsocket.sendto(request, (0, 0))
response = nlsocket.recv(bufsize)
This functionality may be used to compile and debug requests.
=> nlsocket: CompileContext

.github/workflows/pull_request.yml
Don't run linter on the ubuntu runner, some obscure git
related error prevents pre-commit from running there.
=> ci: restrict linter to the code runners

examples/policy/policy.py, pyroute2/netlink/__init__.py, pyroute2/netlink/generic/__init__.py
Add basic support for dumping the policy data that the kernel can report
via CTRL_CMD_GETPOLICY.
The current implementation for parsing the mappings is a bit awkward since
it relies on a list comprehension to fill in the nla_map used.
This is done because the kernel presents some of the sections with nested
NLA where the attribute number is actually an index or a command opcode,
rather than using an extra attribute. Ideally, the nla or nlmsg classes
would be expanded to support this kind of nested substructure.
Eventually we probably want to extract the policy data into more useful
structures. In particular, converting the command opcodes and attribute ids
into human readable names would be ideal.
Add a very basic example which simply dumps and prints the policy data for
the nlctrl …
=> generic: add support for dumping policy

Makefile
run `clean` target only with standard system utilities
=> makefile: don't use sphinx to clean

pyroute2/iproute/linux.py, pyroute2/netlink/rtnl/rtmsg.py, pyroute2/requests/route.py
This PR adds the support for the SRv6 End.DT46 behavior.
The SRv6 End.DT46 behavior is used to implement L3VPN use-cases in multi-tenants environments. It decapsulates the received packets and it performs IPv4 or IPv6 routing lookup in the routing table of the tenant.
The SRv6 End.DT46 behavior has been introduced in the Linux kernel in the commit [1] and it is available since kernel version 5.15.
The iproute2 suite has been extended as well for supporting the SRv6 End.DT46 behavior [2].
An example iproute2 command to instantiate an SRv6 End.DT46 behavior is the following:
`  $ ip -6 route add 2001:db8::1 encap seg6local action End.DT46 vrftable 100 dev vrf100.`
In the above command, the `vrftable` attribute indicates the routing table associated with the VRF device used by SRv6 End.DT46 …
=> Add support for the SRv6 End.DT46 behavior

examples/nftables_sets.py, pyroute2/netlink/nfnetlink/nftsocket.py, pyroute2/nftables/main.py
Hello @svinota, this is a draft for the issue #1013 (implementation of sets and set_elements for Nftables)
=> Draft: Nftables sets

pyroute2/dhcp/__init__.py
Looks like this string literal didn't get changed over to be a byte string during the python3 transition.
=> dhcp/__init__.py: fix bytes vs. str in literal

setup.cfg
prometheus_ss_exporter depends on the logic also as module.
Installing it as cli and tool makes it accessible conventiently to both ways of consumption.
=> install ss2 as module as well

pyroute2/netlink/nl80211/__init__.py
Hello @svinota, I implemented parsers for somes BSS trames (RSN, HT_OPER, VHT_OPER) for getting more information on scan result with iw.
the goal was to be able to recover bandwidth and ciphers like in this example:
```json
"vht_operation": {
"CENTER_FREQ_SEG_1": 42,
"CENTER_FREQ_SEG_2": 42,
"VHT_BASIC_MCS_SET": [
255,
255
],
"CHANNEL_WIDTH": "80 MHz"
},
"rsn": {
"version": 1,
"group_cipher": null,
"pairwise_cipher": [
"CCMP"
],
"auth_suites": [
"SAE"
],
"capabilities": [
"1-PTKSA-RC",
"1-GTKSA-RC"
],
"pmkid_ids": null,
"group_mgmt_cipher_suite": null,
"group_cipher_str": "CCMP"
}
```
=> Nl80211 bss rsn ht oper vht oper

pyroute2/iproute/linux.py, tests/test_linux/test_ipr/test_link.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1065
=> iproute: support altname in link_lookup

pyroute2/ethtool/ethtool.py, pyroute2/ethtool/ioctl.py, tests/test_linux/test_ethtool.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1079
=> ethtool fd leaks

pyroute2/netlink/diag/ss2.py
Move execpton handling further up and catch further perceived exception cases that disturb the user context during forming.
=> ss2 - catch further user context instabilities

pyroute2/netlink/diag/__init__.py
I currently use `inet_diag_msg` to look up the class id of sockets from the application's net_cls cgroup and I've been decoding the hex string, but always meant to make a PR to fix it to be uint32. I'm now upgrading the system to cgroup v2, so I need to move to cgroup id instead which required adding additional fields.
You can see where these are set upstream in the kernel here: https://github.com/torvalds/linux/blob/ac9a78681b921877518763ba0e89202254349d1b/net/ipv4/inet_diag.c#L170-L177
These fields are populated when you request the TCLASS extension.
=> Add support for CGROUP_ID to inet_diag_message and fix type for CLASS_ID

pyroute2/lab.py
The issue is that unittest may not be provided on embedded platforms, though it is included in the minimal build. This is a workaround, a proper fix should exclude lab module from the minimal build.
Bug-Url: https://github.com/svinota/pyroute2/pull/1096
=> lab: postpone unittest import error

pyroute2/netlink/rtnl/tcmsg/sched_netem.py
Just like the loss option, the duplicate option is given as a percentage so we should convert that percentage to a value in before using it.
=> sched_netem: fix duplicate attribute value for netem qdisc

pyroute2/netlink/rtnl/ifinfmsg/__init__.py, pyroute2/netlink/rtnl/ifinfmsg/plugins/can.py
Adds handling of all the attributes related to CAN.
I was not able to figure out how create an interface similar to the iproute package, so the interface is a bit more low level in that instead of adding bitrate with "bitrate=<rate>" one has to package a can_bittiming dict with {"bitrate": <rate>}.
The attribute CAN_CLOCK is a struct of one member in the ABI, but it doesn't seem that fields support one-member structs.
A couple of the attributes haven't been tested because I do not have any dongles that support them. E.g. the TDC options.
Fixes #1023
=> Introduce netlink/rtnl CAN support

util/update_version.py
Avoid retrieving the version from an upper Git repository in case pyroute2 files are simply copied in the said repository, and not cloned.
=> setup: Improve version retrieval from git describe

pyroute2/netlink/devlink/__init__.py, pyroute2/netlink/event/__init__.py, pyroute2/netlink/generic/l2tp.py, pyroute2/netlink/generic/wireguard.py, pyroute2/netlink/nl80211/__init__.py, pyroute2/netlink/taskstats/__init__.py
Currently, most subclasses of GenericNetlinkSocket do not pass unused args up to GenericNetlinkSocket.__init__.
One use case of this is to pass fileno= with an existing file descriptor that was opened in another process/network namespace.
This patch fixes the following subclasses
- EventSocket
- NL80211
- DevlinkSocket
- L2tp
- WireGuard
by passing up *args and **kwargs.
We also fix TaskStats by simply removing the __init__ method that just calls super.
We did not need to fix MPTCP and NlEthtool as they don't overwrite __init__.
=> Allow passing args up to GenericNetlinkSocket constructor

pyroute2/iproute/linux.py
On Linux when calling dump the MPLS routes are not fetched from the kernel.
Add MPLS as well so it is present in NDB on startup.
=> iproute: linux dump mpls routes

pyroute2/iproute/linux.py
I need to assign a nsid to peer netns and it looks like that pyroute2 is currently missing a `RTM_NEWNSID` (`ip netns set`) implementation. However, I am not sure if my approach for adding this request is good.
=> iproute: add support for netns nsid allocation

pyroute2/netns/__init__.py
The method bellow can be used to verify the modification in riscv64.
1. Create a test.py file with the following content. 
```
from pyroute2 import IPDB, NetNS
with IPDB(NetNS("test")) as ipdb_ns:
print(ipdb_ns)
```
2. Run the following command to see if there exists any error. 
```
ip netns add test
python3 test.py
```
=> Fix "failed to open netns" error in RISCV64.

pyroute2/netlink/generic/l2tp.py, tests/test_linux/test_generic/test_l2tp.py
L2TP does not support using filters on NLM_F_DUMP and always returns all objects. The current get_tunnel/session functions however always use NLM_F_DUMP and set the tunnel/session ids if provided by the caller. These are simply ignored.
This patch fixes get_tunnel and get_session to always require specifying the desired tunnel/session id to always get one requested object. If the requested object does not exist an NetlinkError is thrown.
To also provide a way to get all tunnels/sessions dump_tunnels and dump_sessions has been introduced.
---
Note that does does change the signature of `get_tunnel` and `get_session`. I've also adjusted the return value to return the one `l2tpmsg` message we get, so users don't need a odd `[0]` anymore.
=> l2tp: Fix get_tunnel/get_session to return only requested object

Makefile, tests/test_linux/test_generic/test_l2tp.py, tests/test_linux/test_ndb/test_chaotic.py
The reason for using only the system nox is that nox in virtualenv cannot manage python versions, while we have to test multiple versions.
=> makefile: use only system nox

pyroute2/ethtool/ethtool.py, pyroute2/ethtool/ioctl.py, pyroute2/netlink/generic/ethtool.py
Added support to be able to modify and display the ring parameters in ethtool like we would do using `ethool -g` for display and `ethtool -G` for modification
By default we would try to use netlink for the ring operations with a fallback to ioctl in case netlink is not supported:
=> ethtool: add ring support to ethtool

pyroute2/ndb/objects/neighbour.py
I found out that brmsg_schema has unique index on (ifindex, lladdr, vlan), so that gives an answer to me what happend in the linked issue.
There can be multicast FDBs with single ifindex and no NDA_VLAN at all (that means NDA_VLAN = 0), but NDA_DST will be different.
We can clearly see that in the example from the issue:
```
~# bridge fdb show | grep 00:00:00:00:00:00
00:00:00:00:00:00 dev vxln7 dst 10.1.0.107 self extern_learn permanent
00:00:00:00:00:00 dev vxln7 dst 10.1.0.11 self extern_learn permanent
```
This change of index breaks backward compatibility for filters like this:
```python
fdb = ndb.fdb.dump()
fdb.select_records(dst=lambda dst: dst is not None)
do_something_with(list(fdb))
```
Now it's more like identity check:
```python
fdb.select_records(dst=lambda dst: dst)
``` …
=> ndb: make non-unique FDB index more unique

pyroute2/ndb/source.py, tests/test_linux/test_ndb/test_sources.py
The following code snippet gives me an error, but with other objects that works fine.
```python
>>> from pyroute2 import NDB
>>> ndb = NDB()
>>> ndb.sources
AttributeError: type object 'Source' has no attribute '_count'
list(ndb.sources)
AttributeError: type object 'Source' has no attribute '_count'
```
With this patchset applied I got the following output:
```python
>>> ndb.sources
NDB view for sources
Number of objects: 2
to list objects use .summary() or .dump()
-> RecordSet (generator)
-> Record
key: Union[Record, dict, spec]
to get objects use ...[key] / .__getitem__(key)
-> RTNL_Object
>>> list(ndb.sources)
['localhost', 'localhost/nsmanager']
```
The reason behind the absence of this method is that `Source` subclasses `dict`, and there is no real interface in terms of typing that …
=> Fix NDB Source object's counting and update documentation

pyroute2/cli/console.py, pyroute2/ndb/cli.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1161
=> cli: remove readline import

pyroute2/remote/iproute.py
So the `RTNL_API.dump()` will work correctly
=> remote: fix IPRoute groups for RemoteIPRoute

.github/workflows/pull_request.yml, Makefile, README.contribute.rst, noxfile.py, setup.cfg
Run different test modules on different platforms
=> ci: generic make test

pyroute2/iproute/linux.py, pyroute2/ndb/objects/interface.py, pyroute2/netlink/rtnl/probe_msg.py, pyroute2/requests/probe.py
Fixes issue: https://github.com/svinota/pyroute2/issues/1178
=> ndb e1178 link rename

pyroute2/ndb/schema.py
When modifying an existing route with a different
Gateway and Interface the current code does not query the existing route correctly from the database.
Hence we end up with 2 routes in the database instead of replaceing the existing one.
We need to specifically limit the count query to the unique attributes of a route that is replaced which are DST, DST_LEN, Priority and Table.
Signed-Off-By: Sven Auhagen <sven.auhagen@voleatech.de>
=> NDB: Route Replace Error

pyroute2/netlink/rtnl/tcmsg/sched_htb.py, tests/test_linux/test_tc/test_htb.py
Fixes: https://github.com/svinota/pyroute2/issues/1142
=> tca htb rate64

pyroute2/ndb/objects/address.py
Currently only direct routes are removed from the database if the last interface address is removed.
We also need to delete next hops that are associated with the interface and afterwards remove
routes without next hops.
Signed-Off-By: Sven Auhagen <sven.auhagen@voleatech.de>
=> NDB: Address removed netlink message

pyroute2/ethtool/ethtool.py, pyroute2/ethtool/ioctl.py
Add simple setter/getter for ETHTOOL_CHANNELS
exemple:
```
>>> from pyroute2.ethtool import Ethtool
>>> with Ethtool() as tool:
...     print(tool.get_channels('eth0'))
...
EthtoolChannels(max_rx=0, max_tx=0, max_other=1, max_combined=2, rx_count=0, tx_count=0, other_count=1, combined_count=1)
>>> with Ethtool() as tool:
...     tool.set_channels('eth0', {'combined_count': 2})
...     print(tool.get_channels('eth0'))
...
EthtoolChannels(max_rx=0, max_tx=0, max_other=1, max_combined=2, rx_count=0, tx_count=0, other_count=1, combined_count=2)
>>>
```
Thoses fonctionnalities can be found with `ethtool -l` and `ethtool -L`
=> ethtool: add get/set channels functions

pyroute2/ndb/objects/neighbour.py
**Closes**: #1159
I didn't read logs carefully, unfortunately :)
Every time we got FDB missing we got the following 3 reschedules followed by drop as well:
```
2024-06-27 10:30:36,747    DEBUG pyroute2.ndb.139893147176048.main: reschedule {'family': 7, '__pad': (), 'ifindex': 28, 'state': 128, 'flags': 2, 'ndm_type': 0, 'attrs': [('NDA_LLADDR', '1c:34:da:3c:71:2c'), ('NDA_IFINDEX', 28), ('NDA_DST', ''), ('NDA_VLAN', 0)], 'header': {'length': 40, 'type': 28, 'flags': 2, 'sequence_number': 257, 'pid': 4060981674, 'error': None, 'target': 'localhost', 'stats': Stats(qsize=0, delta=0, delay=0), 'rcounter': 1}, 'event': 'RTM_NEWNEIGH'}
2024-06-27 10:30:37,040    DEBUG pyroute2.ndb.139893147176048.main: reschedule {'family': 7, '__pad': (), 'ifindex': 28, 'state': 128, 'flags': 2, 'ndm_type': …
```
=> ndb: fix FDB non-uniquness on different FLAGS

pyroute2/netlink/nfnetlink/ipset.py
reason:
Since I wish to support add multiple ip address in one request, as `ipset restore` does, using nested attributes, the `IPSET_ATTR_LINENO` is required, and his correct data type should be `be32`
as you can see in netlink's header file:
`[IPSET_ATTR_LINENO]	= { .type = NLA_U32 },`
=> fix(ipset): change ipset attr line number to be32

pyroute2/netlink/connector/cn_proc.py
This is useful to be able to set e.g. `async_cache` without needing to manually call `ConnectorSocket.bind`.
=> connector.cn_proc: support kwargs for bind

tests/test_repo/test_version.py
Fixes the repo test by switching dependencies from setuptools._vender.packaging to packaging.version. Please let me know if this is the wrong approach or if I have missed something.
=> Fixing Repo Test

pyroute2/netlink/rtnl/tcmsg/sched_cake.py, tests/test_repo/test_version.py
Hello pyroute2 team,
This PR was created to propose a solution to a behavior in the cake tc plugin wherein tc pops off the 'parent' key from kwarg and onto msg:
```
if kind in tc_plugins:
p = tc_plugins[kind]
msg['parent'] = kwarg.pop('parent', getattr(p, 'parent', 0))
if hasattr(p, 'fix_msg'):
p.fix_msg(msg, kwarg)
if kwarg:
if command in (RTM_NEWTCLASS, RTM_DELTCLASS):
opts = p.get_class_parameters(kwarg)
else:
opts = p.get_parameters(kwarg)
else:
msg['parent'] = kwarg.get('parent', TC_H_ROOT)
```
Then, when hasattr(p, 'fix_msg') is evaluated, the kind cake does have a p attribute, which cake does have, and it drops into fix_msg:
```
def fix_msg(msg, kwarg):
if 'parent' not in kwarg:
msg['parent'] = TC_H_ROOT
```
Which, because it just popped 'parent' from kwarg, it is always not …
=> Fix TC Cake Plugin

pyroute2/netlink/connector/cn_proc.py
change `proc_event_uid` and `proc_event_gid` to return `ruid/euid` and `rgid/egid` respectively.   currently the values are using the union of each event type.
great feature by the way!
=> switch euid/ruid field names for uid/gid events

pyroute2/iproute/ipmock.py
Pylint is reporting a false positive unexpected-keyword-arg. At first I thought it was a pylint bug, so I reported it: https://github.com/pylint-dev/pylint/issues/9922. But as it turned out, the bug is in the ipmock module inside pyroute2. Some functions lack a **kwarg parameter, so it needs to be added there, that's why I created this PR.
=> Adding kwarg parameter to ipmock

pyroute2/netlink/rtnl/ifinfmsg/__init__.py
Fixes #1227 reported by me earlier
add the following new options:
IFLA_BRPORT_MCAST_EHT_HOSTS_LIMIT
IFLA_BRPORT_MCAST_EHT_HOSTS_CNT
IFLA_BRPORT_LOCKED
IFLA_BRPORT_MAB
IFLA_BRPORT_MCAST_N_GROUPS
IFLA_BRPORT_MCAST_MAX_GROUPS
IFLA_BRPORT_NEIGH_VLAN_SUPPRESS
IFLA_BRPORT_BACKUP_NHID
=> ifinfmsg: add new bridge port options

pyroute2/requests/link.py, tests/test_unit/test_requests/test_link.py
I submit this pull request which fixes setting the state and noarp flags in LinkFieldFilter. Previously, the flags were not combined together due probably due to an operator precedence oversight.
First, a commit introduces two tests:
- A trivial `state='up'` test which passes
- A combined `state='up'` and `noarp=True` test which fails due to LinkFieldFilter failing to combine the two flags
Then, a further commit fixes the underlying issue:
- Parenthesization fixes the operator precedence issue
- The hardcoded value `1` is replaced with constant `IFF_UP`
=> fix state and noarp flag setting in LinkFieldFilter

pyroute2/netlink/rtnl/tcmsg/sched_htb.py
Since commit b731fca9d2a3f598145d5f41fa04f7b3ae32ac88 rate cannot be None anymore:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
=> tcmsg/sched_htb: rate and ceil are optional

pyroute2/iproute/linux.py, tests/test_core/pr2test/tools.py, tests/test_core/test_ipr/test_tc_async.py
The old version could filter qdiscs by the interface index, fix that in the new API.
Bug-Url: https://github.com/svinota/pyroute2/issues/1225
=> tc: fix get_qdiscs(index=...)

pyroute2/requests/rule.py, tests/test_core/pr2test/tools.py, tests/test_core/test_ipr/test_rule_async.py, tests/test_core/test_ipr/test_rule_sync.py
Don't set src/dst len if src/dst absent or is None
Bug-Url: https://github.com/svinota/pyroute2/issues/1246
=> requests: fix rule (src|dst)(_len)

pyroute2/netlink/rtnl/ifinfmsg/__init__.py
The kernel expects a 4-byte in host-endian format, but '>H' in Python sends a 2-byte in big-endian format.
https://github.com/torvalds/linux/blob/21266b8df5224c4f677acf9f353eecc9094731f0/net/core/rtnetlink.c#L3329
=> ifinfmsg: fix xdp flags

pyroute2/dhcp/leases.py, tests/test_linux/fixtures/dhcp_servers/udhcpd.py, tests/test_linux/test_dhcp/test_integration.py
I had overlooked a critical part of the RFC and forgot to compute default values for renewal & rebinding times; not all servers provide these. So the lease expired again and again.
=> dhcp client: add missing default values for rebinding & renewal times

pyroute2/common.py, tests/test_unit/test_addr_pool.py, tests/test_unit/test_common.py
Deletion of unused code in `pyroute2/common.py`:
- Python 2 related chunk
- Classes: `View` and `DotKeys`
- Functions: `hexload`, `_fnv1_python2` and `failed_class`
- Constants: `AF_PIPE` and `DEFAULT_RCVBUF`
Take extra attention to deletion of:
- `AddrPool.allocated`
- `AddrPool.alloc_multi`
- `AddrPool.setaddr`
...because I hope I checked usage of these attributes, however, I am not 100% sure
=> Delete unused code from `./common.py`

pyroute2/netlink/core.py
transport.close() does not really close the socket, but move the transport to "closing" state.
We need to give some time to the event loop for a real closed object
Before the patch:
$ python3 -X dev -c "from pyroute2 import IPRoute ; ip = IPRoute() ; ip.close()"
/usr/lib/python3.11/asyncio/selector_events.py:843: ResourceWarning: unclosed transport <_SelectorDatagramTransport closing fd=6>
=> netlink/core: give a chance for socket to close

pyroute2/dhcp/client.py, pyroute2/dhcp/leases.py
The way it was done, if the interface name had a vlan in it (example eth1.100), since we're using the `with_suffix` function it would remove the vlan and save the files as `eth1.pid` and `eth1.lease.json`
=> dhcp: interface name can have a vlan in it

pyroute2/common.py, tests/test_unit/test_common.py
Couldn't infer type for `msg_done` function.
Linter would warn about two lambda functions, but I saved them, since one of them is actually closure, so that would complicate typing too much.
Other than typing, following changes were done:
- `map_namespace` were re-written to be more explicit. Tests are added
- `load_dump` Python 2 code was removed
=> Types for the `pyroute2.common`

noxfile.py
* `make format` uses the latest available python version
* `make format` within venv uses the venv python version
* `make format python=python3.12` enforces python version 3.12
* `make nox session=linter-python3.12` another way to enforce version
=> linter: cover more python versions

pyroute2/dhcp/dhcp4socket.py, pyroute2/dhcp/fsm.py, pyroute2/dhcp/messages.py, pyroute2/dhcp/server_detector.py, pyroute2/dhcp/xids.py, pyroute2/ext/bpf.py, pyroute2/ext/rawsocket.py, tests/test_linux/test_dhcp/test_server_detector.py
We noticed an issue when using the dhcp server detector over a vlan, i have to test & reproduce it but using a different xid for each interface will help
=> dhcp server detector: use a different xid per interface

pyroute2/ndb/objects/interface.py
Fix setns operations when the netns is not in the sources:
```
with NDB() as ndb:
with ndb.interfaces['port0'] as i:
i['net_ns_fd'] = 'test'
```
OBS: it should work with the source as well:
```
with NDB() as ndb:
ndb.sources.add(netns='test')
with ndb.interfaces['port0'] as i:
i['net_ns_fd'] = 'test'
```
In this case the interface state should be 'system' instead of 'invalid'.
Bug-Url: https://github.com/svinota/pyroute2/issues/1181
=> ndb.objects.interface: fix setns

pyroute2/ethtool/ioctl.py
We stumbled upon a case where the mask is empty, when retrieving the statistics of a virtual interface created on a bonding of two physical interfaces.
In this case, `ethtool` simply return empty statistics, either from ioctl or netlink :
```
Standard stats for eth0:
no stats available
```
And looking at the kernel code, we can see that the mask is first zeroed [1] then filled only on success [2], meaning that an empty mask is possible.
[1]: https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ethtool/ioctl.c#n797
[2]: https://web.git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ethtool/ioctl.c#n814
=> ioctl: Remove assert on mask when retrieving string set info

pyroute2/dhcp/__init__.py, tests/test_linux/test_dhcp/test_parser.py
I made the ill-advised choice to decode unknown DHCP options as raw bytes. This works pretty well as long as you stay within Python but will causes issues when serializing or deserializing. Lists of ints are easy to use and don't cause such issues.
=> dhcp: decode unknown options as list of ints instead of bytes

pyroute2/dhcp/client.py, tests/test_linux/test_dhcp/test_integration.py
In the unlikely event the lease cannot be written to disk (read only file system ? removed working dir ? undumpable JSON ?), the client shouldn't crash but simply log an error. The only consequence is that the client won't load the lease on next startup.
=> dhcp client: do not crash when failing to write a lease

pyroute2/dhcp/__init__.py, tests/test_linux/test_dhcp/test_encode.py, tests/test_linux/test_dhcp/test_parser.py, tests/test_linux/test_dhcp/test_unit.py
This is a fix for an oversight on my part.
The DHCP client stores the whole ACK from the server in its leases.
That means when dumping a lease to a JSON file, all data in the ACK must be serializable.
However, i did not decode byte strings and these can't be JSON-encoded.
This PR changes the decoding logic so that byte strings in options are decoded as strings, and all bytes values are turned to a list of ints if undecodable.
This way, all options can be dumped to JSON successfully.
=> dhcp: decode bytes options as strings or lists to make them JSON encodable

pyroute2/common.py, pyroute2/iproute/linux.py, pyroute2/netns/__init__.py
time.time() is dangerous since in case of clock synchronization:
* it can go backward and produce weird effects
* it can go forward with a big jump
time.CLOCK_BOOTTIME provides safety for timeout checks.
See https://docs.python.org/3/library/time.html#time.CLOCK_BOOTTIME
One drawback: it is only available on Linux, after 2.6.39 version
=> common: introduce time.CLOCK_BOOTTIME to compute timeout

pyroute2/requests/common.py
Hello,
while fixing an issue in another project, I noticed that when I passed both a `dst_len=0` and a (redundant) `dst="0.0.0.0"` into `IPRoute.rule("delete", ...)` pyroute2 would throw an exception.
Specifically, it was `socket.inet_pton` that threw `OSError: illegal IP address string passed to inet_pton`.
After closer inspection, I realized that pyroute2 was passing an empty string to the function, which is invalid in [Linux's implementation](https://www.man7.org/linux/man-pages/man3/inet_pton.3.html).
Following the value backwards, to see where it gets replaced, I'm pretty sure that I found the place in `requests/common.py` (see commit).
Just making it not return any value for `dst` seemed to fix the issue.
I'm not familiar with the codebase but I think the only other place where this …
=> iproute: Fixed the request parser, so that it accepts {'dst_len': 0, 'dst': "0.0.0.0"} without an OSError

pyroute2/iproute/linux.py, pyroute2/netlink/nlsocket.py, pyroute2/netlink/rt_files.py, pyroute2/netlink/rtnl/ifaddrmsg.py, pyroute2/netlink/rtnl/tcmsg/common_ematch.py, pyroute2/requests/address.py, pyroute2/requests/link.py, pyroute2/requests/main.py, pyroute2/requests/route.py, pyroute2/requests/tc.py, tests/test_linux/conftest.py, tests/test_linux/fixtures/rt_file.py, tests/test_linux/test_ipr/test_route.py
Hello @svinota, I implement management of all rt_file of iproute2 [Found on their repository](https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/etc/iproute2)
You can easily replace int value to an str like this:
```python
ipr.route("show", table="main")
ipr.route("show", table="local")
ipr.link("dump", group="default")
...
```
=> Add iproute "rt files" management

pyroute2/netlink/nfnetlink/nftsocket.py
Using `nfgen_family` as a keyword argument overrides the value of `._nfgen_famaily` in the request scope.
Bug-Url: https://github.com/svinota/pyroute2/issues/1366
Bug-Url: https://github.com/svinota/pyroute2/issues/1365
=> nftables: accepting nfgen_family as an argument

pyroute2/netlink/rtnl/ifinfmsg/plugins/geneve.py
This change addresses https://github.com/svinota/pyroute2/issues/1394 by adding support for the `innerprotoinherit` flag for Geneve interfaces.
Created a network interface with
```
ip = IPRoute()
ip.link("add",
ifname="g0",
kind="geneve",
geneve_id=1000,
geneve_remote="172.30.16.26",
geneve_inner_proto_inherit=1)
idx = ip.link_lookup(ifname="g0")[0]
ip.link("set", index=idx, state="up")
```
Before this change, the `innerprotoinherit` flag is dropped: 
```
ip -d link show
g0: <NOARP,UP,LOWER_UP> mtu 8951 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
link/none  promiscuity 0 allmulti 0 minmtu 68 maxmtu 65485 
geneve id 1000 remote 172.30.16.26 ttl auto dstport 6081 noudpcsum udp6zerocsumrx addrgenmode random numtxqueues 1 numrxqueues 1 …
```
=> Add Support for Geneve innerprotoinherit

Makefile, util/find_python.sh
Fix `make ... python=pythonX.Y` to propagate the version to nox as well.
=> ci: propagate python version from make to nox

pyroute2/iproute/ipmock.py
In commit 43206d9b022b137d349e4fa5db167ae261c027ba, while adding support for routes priority, we introduced a new parameter for `MockRoute` called `type`.
However, there was already a parameter called `route_type` which seemingly intended to serve the same purpose. That parameter was used in mock presets, but unfortunately wasn't honored when calling the `.export()` function.
Before this patch the situation was that we had two ambiguous types:
* `route_type`, which is used in mock presets but isn't honored when calling `.export()`. It has a default value of  `RTN_UNICAST`.
* `type`, which is not used in mock presets but would otherwise get honored when calling `.export()`. It has a default value of `RTN_LOCAL`.
Fixed by dropping the redundant `type` parameter and using the value of …
=> ipmock: fix ambiguity with MockRoute's type and route_type params

pyroute2/netlink/rtnl/ndmsg.py
NDA_FDB_EXT_ATTRS was missing.
Add two more attributes.
Fixes: 3540ff1619 ("ndmsg: update nda list")
Link: https://github.com/torvalds/linux/blob/v6.14/include/uapi/linux/neighbour.h#L31
Link: https://github.com/svinota/pyroute2/pull/1424#r2367488141
=> ndmsg: fix update nda list

pyroute2/dhcp/dhcp4socket.py, pyroute2/dhcp/server_detector.py
I'm using the DHCPServerDetector directly to help me with provisioning commercial off-the-shelf routers, it's a great help, so thanks for the implementation. However, I noticed using detect_servers() was rather leaky with regards to cleaning up certain async tasks, presumably because the main usage is as a CLI tool, where it matters less. But because the leftover tasks were cluttering up my logs with various error messages, here are two commits to improve the usage of detect_servers() through plain Python.
I'm not too familiar with the development side of this project, so if I missed something important, do let me know and I'll happily correct whatever is needed.
=> Improve cleanup of DHCP server detector tasks
