svinota/pyroute2

pyroute2/netlink/nlsocket.py
Due to layers of __getattr__ games, socket.socket isn't particularly
subclass friendly, and GreenSocket (from eventlet) is slightly worse.
This change just gives up on inheritance-for-implementation and
delegates socket methods to an arms-length object.
Note this change sets explicit wrapper methods rather than relying on
__getattr__ at run-time, since the latter won't support `super().foo`
calls if a subclass has overridden `foo`.
In particular, the new class can still be used in select() and friends
directly due to the fileno() method.
=> Use socket via composition rather than inheritance

pyroute2/iwutil.py, pyroute2/netlink/generic/__init__.py, pyroute2/netlink/nl80211/__init__.py, pyroute2/netlink/nlsocket.py
Add listening possibility to nl80211 event
Implement listWiPhy and getInterfaceByPhy method
=> nl80211 ci

pyroute2/iwutil.py, pyroute2/netlink/__init__.py, pyroute2/netlink/nl80211/__init__.py
Begin decode the NL80211_BSS_ELEMENTS binary elements (rated, channel and ssid)
=> Add the scan Wifi implementation

pyroute2/netns/__init__.py
Previously this code raised OSError exceptions with code errno.ECOMM for
all libc calls via ctypes except the setns syscall where it always used
code '-1'.
This change faithfully propagates the C errno value.
=> Return correct errno codes from libc ctypes calls

pyroute2/iwutil.py, pyroute2/netlink/nl80211/__init__.py
This pull request implements three functions `get_stations`, `join_ibss`, and `leave_ibss`.
=> Implement three functions for iwutil

pyroute2/ipdb/__init__.py
=> Fixed spelling typo in docstring

pyroute2/netlink/rtnl/ifinfmsg.py
* See https://patchwork.ozlabs.org/patch/493787/
Signed-off-by: Brenden Blanco <bblanco@plumgrid.com>
=> Add support for lwtunnel vxlan flags

pyroute2/netlink/rtnl/ifinfmsg.py
Support added in https://patchwork.ozlabs.org/patch/502386/
Signed-off-by: Brenden Blanco <bblanco@plumgrid.com>
=> Add VXLAN_COLLECT_METADATA flag to rtnl

pyroute2/netlink/rtnl/tcmsg/sched_hfsc.py
Just a small fix, I saw most of the parsing logic was already in place. Haven't found any other issues with the HFSC module in master so far! :+1:
=> Parse hfsc "d" parameter as time unit

pyroute2/ipset.py, pyroute2/netlink/nfnetlink/ipset.py, tests/general/test_ipset.py
Add basic support for ipset options (comment, counters, forceadd, maxelem, hashsize).
All features are tested.
=> Add some Ipset options

pyroute2/netns/__init__.py, pyroute2/netns/nslink.py, tests/general/test_netns.py
A test has been added to validate creating a NetNS object using the
path of an existing namespace.
=> netns: test cases for the custom netns path

pyroute2/dhcp/dhcp4msg.py
Add 3 dhcp options, `lease_time` especially.
=> dhcp4msg: support `lease_time`, `renewal_time` and `rebinding_time`

pyroute2/ipset.py, pyroute2/netlink/nfnetlink/ipset.py
Hello,
One more pull requests for ipset part. It helps to manage several ipset types with the same ipset attribute, and to check features supported by running kernel.
=> Ipset revisions

docs/debug.rst
Hello,
This is a PR for issue #337, I added a section in debug.rst to warn about the incompatibility.
=> warn about strace's >= 4.13 incompatibility with the documented debug method

pyroute2/netlink/rtnl/tcmsg/act_mirred.py, pyroute2/netlink/rtnl/tcmsg/common_act.py, tests/general/test_tc.py
Hello,
I added the mirred action for tc, and wrote a test for it.
Not being quite sure where to put the test, I added a TestActions class to test_tc.py, tell me if there's anything wrong with the test and I'll fix it.
=> tc mirred action

pyroute2/iproute.py
They differ from the semantics of "change" from the "tc" tool.
=> tc: explain the semantics of "change"

pyroute2/ipdb/routes.py
=> ipdb: Handle IPv6 tables >= 256

pyroute2/ipset.py
Added ipset support for settype: bitmap:*
Only tested with bitmap:port
`[root@localhost pyroute2]# git log -1 --pretty=oneline
4d1e25d2947ed98212dcb7ff6bbcf1e17b5a4873 Added bitmap support for ipset structure type
[root@localhost pyroute2]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ipset import IPSet
>>> a = IPSet()
>>> a.create(name='testbitmap1', stype='bitmap:port', bitmap_range='0-10000')
[root@localhost pyroute2]# ipset list
Name: testbitmap1
Type: bitmap:port
Revision: 1
Header: range 0-10000
Size in memory: 80152
References: 0
Members:
`
=> Added bitmap support for ipset structure type

pyroute2/netlink/rtnl/req.py, pyroute2/netlink/rtnl/rtmsg.py
Changes:
- Introduces IPRoute support for seg6 tunnel
- Adds encap and inline modes
- Supports hmac functionality for SRH
- Initial parsing of human friendly form
- Add seg6_encap_info for RTA_ENCAP mgmt
=> Adds seg6 support

README.md, pyroute2/netlink/rtnl/req.py
=> Improves seg6 documentation

pyroute2/ipdb/main.py, pyroute2/netlink/rtnl/ifinfmsg/plugins/vti6.py, tests/general/test_ipr.py
=> add vti6 support

pyroute2/netlink/rtnl/fibmsg.py
=> add NLA number for l3mdev rules

pyroute2/ipset.py
Apologies, fixing my syntax error I introduced. I might look at writing some tests.
=> Corrected syntax error for new attribute for create ipset

pyroute2/netlink/rtnl/req.py, pyroute2/netlink/rtnl/rtmsg.py
Hi,
This PR adds support for the LWT BPF encap functionality. Format samples are provided in the code. Handles LWT_BPF_IN, LWT_BPF_OUT and LWT_BPF_XMIT (with headroom).
Don't hesitate to tell me if something needs to be changed.
Thanks.
=> Add support of LWT BPF encap

pyroute2/netlink/nfnetlink/conntrack.py
Hi,
This PR adds support for the `conntrack` capability.
Thanks.
=> nfnetlink: add conntrack capability

pyroute2/conntrack.py
Hi,
This PR adds a high-level API to obtain statistics of conntrack  into the class `Conntrack`.
Thanks.
=> conntrack: add high-level API for stat()

cli/ss2.py
Signed-off-by: Matthias Tafelmeier <matthias.tafelmeier@gmx.net>
=> ss2: add minimal sk states filtering

pyroute2/netns/nslink.py, pyroute2/remote/__init__.py, tests/general/test_stress.py, tests/utils.py
Hi, I added unit tests for the patch, and also found that we don't need the workaround for  https://github.com/svinota/pyroute2/issues/400 anymore, so deleted related code in the patch.
Bug-Url: #501
=> Fix NetNS Resource Leakage

pyroute2/netlink/nl80211/__init__.py
Decode the data retrieved when getting information about a station.
See `nl80211.h`, `enum nl80211_sta_info`.
=> nl80211: Decode data retrieved when getting information about a station.

benchmark/ipdb-route.py, benchmark/ipdb.py, docs/conf.py
Just needed to get this flake8 compatible
=> Fixes for flake8 checks

pyroute2/netlink/rtnl/tcmsg/__init__.py, pyroute2/netlink/rtnl/tcmsg/cls_flow.py, pyroute2/netlink/rtnl/tcmsg/common.py
Add support for TC filter flow
=> Filter flow

cli/ss2
Associating pertaining sockets with context holding those via fds.
Signed-off-by: matthias <matthias.tafelmeier@gmx.net>
=> ss2: extend for usr context association

pyroute2/iproute/linux.py, pyroute2/netlink/rtnl/ifinfmsg/__init__.py
Hi!
Add basic support for tunnel ipip, sit and ip6tnl.
Tell me if anything is missing!
Thanks!
=> rtnl: add ipip/sit/ip6tnl support

pyroute2/netlink/__init__.py, tests/general/test_netns.py
The clean_cbs dict in netlink/__init__.py uses seq as the key. When
pyroute2 is used in multithread programe, each thread get's its own
AddrPool and the seq always starts from 0x000000ff. If clean_cbs is not
stored in thread local storage, it's possible for threads happen to get
the same seq and register cleanup under the same key. So if one thread
does its cleanup, it frees the resources owned by other threads.
In this patch we store the cleanup table in thread local storage to
avoid the problem. Other global variables in netlink/__init__.py don't
suffer similar race conditions, so no need to change.
Bug-Url: https://github.com/svinota/pyroute2/issues/547
Signed-off-by: Zhengsheng Zhou <zhengshengz@vmware.com>
=> Use threading.local to Store Cleanup Callback Dict

pyroute2/__init__.py
This will make version checking easier for users.
closes #576
Signed-off-by: Antoni Segura Puimedon <celebdor@gmail.com>
=> Include __version__ in the pyroute2 package

pyroute2/wiset.py, tests/general/test_wiset.py
Hello,
I added the support for skbinfo in the wiset ipset helper.
You can add entries with skbmark as tuple like for ipset or as a string as in the ipset command documentation.
I also added one test in the test_wiset.py file.
Best regards
Charles DAYMAND
=> Skbinfo in wiset

pyroute2/netns/__init__.py
=> Fix IPDB + NetNS usage example to also close() NetNS instance after use

examples/nl80211_scan_dump.py, pyroute2/netlink/nl80211/__init__.py
decode TSF, Signal strength, Capabilities
add example/nl80211_scan_dump.py to (partially) mimic 'iw dev scan dump'
(work in progress)
=> decode more WiFi nl80211 scan results fields

pyroute2/__init__.py, pyroute2/netlink/generic/wireguard.py
Add basic support for parser and configuration management
=> WireGuard: add basic support

pyroute2/netlink/rtnl/rtmsg.py
=> rtnl: fix type of RTA_PREF

examples/ipset.py
Added IPset example to save another newbie some time
=> Added IPset example

pyroute2/netlink/rtnl/tcmsg/act_skbedit.py, pyroute2/netlink/rtnl/tcmsg/common_act.py
These commits add support for skbedit action.
=> skbedit: add action support

pyroute2/netlink/rtnl/tcmsg/__init__.py, pyroute2/netlink/rtnl/tcmsg/sched_cake.py
This pull request adds support for tc-cake into pyroute2.
=> cake: add support for cake scheduler

pyroute2/netlink/generic/wireguard.py
Since the update of the WireGuard code now using .NLA_EXACT_LEN attributes (see https://github.com/WireGuard/WireGuard/blob/19b2fb70620d5d664549b1e9dd5f123ab1a1baf5/src/netlink.c#L32), header types of the following classes are not correctly set when encoding NLAs:
wgpeer_a_allowedips
wgpeer_allowedip
wgdevice_a_peers
wgdevice_peer
So I forced them, taken from dumps of netlink messages using the 'wg' command.
I don't know if it's really related with .NLA_EXACT_LEN attributes but I did not understand how these values are built.
It also includes a fix for Python2 and empty IPv6 endpoint address.
=> WireGuard: multiple fixes

pyroute2/netlink/rtnl/tcmsg/cls_basic.py, pyroute2/netlink/rtnl/tcmsg/common_ematch.py, pyroute2/netlink/rtnl/tcmsg/em_cmp.py
This patch adds support for cmp ematch.
=> tc/basic: add cmp ematch support

pyroute2/netlink/rtnl/tcmsg/cls_basic.py, pyroute2/netlink/rtnl/tcmsg/common_ematch.py, pyroute2/netlink/rtnl/tcmsg/em_meta.py
This patch adds meta ematch support for basic filter.
=> tc/meta: add meta support

Makefile, README.md, cli/ss2, setup.py
Declare psutil in `extras_require` and raise an exception if it is
not present in the system
Bug-Url: https://github.com/svinota/pyroute2/pull/679
=> ss2: make an extra

pyroute2/ethtool/ethtool.py, pyroute2/ethtool/ioctl.py
Hello, there was some littles bug on ethtool for get/set features, theses patches correct them
=> Ethtool features fixes

pyroute2/iproute/linux.py, pyroute2/netlink/rtnl/ifinfmsg/__init__.py, pyroute2/netlink/rtnl/ifinfmsg/plugins/geneve.py
This PR adds encodig/decoding support for geneve tunnels. I am not sure if the type mappings are all correct.
=> rtnl: Add geneve support.

pyroute2/netns/__init__.py, tests/general/test_netns.py
iproute2 has added the handy `attach` command to the `ip netns` cli, so this adds an attach function to the netns module to provide the same useful behavior.
=> netns: attach fn to create named netns from pid

pyroute2/netlink/nfnetlink/nftsocket.py
Hello!
I'm happy to submit a merge request to improve the parsing of nft messages, which should correspond to what is defined in linux 5.10.7.
This code has been tested over a fairly complex ruleset, and seems to parse messages successfully without any unknown field.
For reference, I think the only things missing after this pull request is applied are:
* `nft_ct_*`
* `nft_object_...`
* `nft_tunnel...`
* support for tracing (`nft monitor`)
Thanks a lot!
Laurent
=> Extend nftables netlink messages (linux 5.10.7)

tests/general/test_nftables.py
replaced with "nft -j list ruleset"
=> "nft" no longer supports "export json"

.deepsource.toml, pyroute2/cli/parser.py, pyroute2/ethtool/ioctl.py, pyroute2/ipset.py, pyroute2/ndb/objects/__init__.py, pyroute2/ndb/objects/route.py, pyroute2/netlink/__init__.py, pyroute2/netlink/nfnetlink/nfctsocket.py, pyroute2/netlink/rtnl/ifinfmsg/__init__.py, pyroute2/netlink/rtnl/rtmsg.py, pyroute2/netlink/rtnl/tcmsg/sched_codel.py, pyroute2/netlink/rtnl/tcmsg/sched_fq_codel.py, pyroute2/netns/manager.py, pyroute2/nftables/parser/parser.py, tests/collector.py, tests/general/test_ipdb.py
Hey :wave:, I'm a Developer Outreach at DeepSource and ran DeepSource analysis on my fork of the repo. It found some interesting [code quality and performance improvements](https://deepsource.io/gh/akshgpt7/pyroute2/) to consider.
This PR fixes a few of the issues detected for you to assess if it is right for you.
Happy to provide the tweaks separately otherwise :)
- Remove unnecessary generator.
- Iterate dictionary directly instead of using `.keys()`.
- Remove calling `len()` for comparison.
- Use literal syntax instead of function calls to create data structure.
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.
=> Refactor code quality issues

pyroute2/netlink/rtnl/tcmsg/sched_netem.py
Add support for netem rate settings:  rate, packet_overhead, cell_size and cell_overhead
=> Add support for netem rate setting

pyroute2.core/pr2modules/iwutil.py, pyroute2.core/pr2modules/netlink/nl80211/__init__.py
=> nl80211: allow to get and set regulatory rules

pyroute2.ndb/pr2modules/ndb/objects/interface.py
This determines whether a given interface "points to" another. It is relevant to vlans and veths.
This also fixes #835.
=> [ndb] Add is_peer() method for interface objects

pyroute2.ndb/pr2modules/ndb/main.py
=> [ndb] Set context for lookup key in exists() method

pyroute2.ndb/pr2modules/ndb/objects/interface.py
If a netlink event is received for an interface which no longer exists, print a debugging message and swallow the exception.
See #861.
=> [ndb] Handle exceptional case when interface disappears

pyroute2.core/pr2modules/netlink/generic/wireguard.py
Hello svinota I hope you are fine, recently I used wireguard with ipv6 but I ran into some bugs and this pull request correct this.
Have a good day,
=> Wireguard some fixes for ipv6

pyroute2.core/pr2modules/netns/__init__.py
When setns (and other libc functions) are called repeatedly, they load libc at every function call, which results in a lot of I/O overhead.
This fix allows the loaded libc module to be cached globally and fetched later when required.
=> Fixed unnecessary reloading of libc

.github/workflows/pull_request.yml, .gitignore, .pre-commit-config.yaml, examples/lab/example1/check.py, examples/lab/example1/setup.py, examples/lab/example1/task.py, lab/Makefile, lab/_static/custom.css, lab/_static/fixup.js, lab/_static/lab.js, lab/_templates/layout.html, lab/conf.py, lab/index.rst, lab/iproute.rst, noxfile.py, pyroute2/iproute/__init__.py, pyroute2/iproute/linux.py, pyroute2/iproute/pyodide.py, pyroute2/lab.py, tests/test_lab/conftest.py, tests/test_lab/test_code_blocks.py, util/aafigure_mapper.py, util/make_lab_templates.py
Fake IPRoute for an online lab.
=> pyodide: a web lab

pyroute2/iproute/linux.py, tests/test_linux/test_ipr/test_neigh.py
=> iproute: fix neighbours dump

Makefile
Run venv by default for all nox operations.
Thus the only requirement in the system will be Python and some
generic Linux utils.
=> setup: don't expect nox in the system

pyroute2/ndb/source.py
Bug-Url: https://github.com/svinota/pyroute2/issues/992
=> ndb.source: persistent -> max_errors

.github/workflows/pull_request.yml, docs/_static/custom.css, docs/conf.py, docs/ndb_init.rst, noxfile.py, pyroute2/ipdb/main.py, pyroute2/iproute/pyodide.py, pyroute2/ndb/main.py, pyroute2/ndb/report.py, pyroute2/wiset.py, setup.cfg
=> docs: integrate doctest

pyroute2/netlink/rtnl/ifinfmsg/plugins/vlan.py, pyroute2/requests/link.py, tests/test_linux/test_ipr/test_vlan.py
+ shortcuts
+ tests
Bug-Url: https://github.com/svinota/pyroute2/issues/1000
=> ifinfmsg: set vlan egress/ingress qos mapping

pyroute2/iproute/bsd.py, pyroute2/iproute/ipmock.py, pyroute2/iproute/linux.py, pyroute2/ndb/source.py, pyroute2/netlink/nlsocket.py, pyroute2/netlink/rtnl/iprsocket.py, pyroute2/netns/manager.py, pyroute2/nslink/nslink.py, pyroute2/remote/transport.py, tests/test_linux/test_ndb/test_init.py
Bug-Url: https://github.com/svinota/pyroute2/issues/995
=> iproute, netns: support netlink_groups

pyroute2/ndb/main.py, pyroute2/ndb/schema.py, pyroute2/ndb/source.py, pyroute2/ndb/view.py
Prepare the schema for the new task manager, remove unnecessary methods publishing.
=> ndb.schema: task manager related fixes

pyroute2/iwutil.py, pyroute2/ndb/objects/interface.py, pyroute2/netlink/nlsocket.py, pyroute2/netlink/rtnl/tcmsg/cls_u32.py, pyroute2/netlink/rtnl/tcmsg/common.py, pyroute2/netlink/rtnl/tcmsg/sched_sfq.py
and replace with more meaningful exceptions
=> general: remove asserts from the prod code

pyroute2/ndb/compat.py, pyroute2/ndb/objects/address.py, pyroute2/ndb/objects/interface.py, pyroute2/ndb/report.py, pyroute2/netlink/nlsocket.py, tests/test_linux/test_ipr/test_route.py, tests/test_linux/test_ndb/test_backup.py, tests/test_linux/test_ndb/test_reports.py, tests/test_linux/test_ndb/test_sources.py, tests/test_linux/test_ndb/test_views.py, tests/test_linux/test_raw/test_dhcp.py
=> ci: cleanup deprecated API usage

pyroute2/ndb/objects/interface.py
wait for the peer to be created
=> ndb: wait for veth peer

pyroute2/netlink/generic/wireguard.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1021
=> wireguard: update docs

pyroute2/iproute/ipmock.py, pyroute2/ndb/objects/interface.py
=> ndb.objects.interface: update docs

pyroute2/ndb/main.py, pyroute2/ndb/objects/interface.py, pyroute2/ndb/objects/netns.py, pyroute2/ndb/schema.py, pyroute2/ndb/task_manager.py
=> ndb: schema refactoring

pyroute2/iproute/linux.py, pyroute2/netlink/nlsocket.py, requirements.docs.txt, tests/test_linux/test_ipr/test_config.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1030
=> generic API to work with request flags

pyroute2/netlink/connector/__init__.py, pyroute2/netlink/connector/cn_proc.py, pyroute2/netlink/nlsocket.py, setup.cfg, tests/test_linux/test_connector/text_cn_proc.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1036
=> basic connector family + proc_event implementation

pyroute2/netlink/nlsocket.py
NetlinkSocketBase.recv uses DEFAULT_RCVBUF to fetch things like ip links via netlink sockets. It happed in the last cycles that with new NICs with higher VF numbers or similar we have to change the buffer size (see #751 or #813).
A better solution (thanks to one or our experts) can be to check the necessary buffer size before receiving the sockets.
Fixes #1044
=> Add _peek_bufsize to NetlinkSocketBase so recv can use it

pyroute2/ndb/objects/route.py, tests/test_linux/test_ndb/test_routes.py
=> ndb.objects.route: support adding metrics

pyroute2/netlink/nlsocket.py
@elajkat pls take a look -- unconditional peek causes BlockingIOError on wireless ops.
I tried to fix, and I hope it doesn't break your cases.
=> nlsocket: fix BlockingIOError on socket peek ops

pyroute2/iproute/linux.py, pyroute2/netlink/rtnl/ifinfmsg/__init__.py, pyroute2/requests/bridge.py
I added to IPRoute.vlan_filter()
1. vlan_tunnel_info to support vxlan vlan/vni mapping
2. support for ranges; add a range of VLAN tags and mappings
3. PVID bool
=> added vlan_tunnel_info, vid ranges, and a pvid bool

pyroute2/iproute/linux.py, pyroute2/netlink/rtnl/ndmsg.py
Added NDA_SRC_VNI to support vlan-aware vxlan tunnels.
=> Added NDA_SRC_VNI to support vlan-aware vxlan tunnels.

pyroute2/requests/bridge.py
Fix an error with VLAN and VNI ranges.
=> fix vid/vni range

setup.py
Bug-Url: https://github.com/svinota/pyroute2/discussions/1053
=> setup: return setup.py to support legacy builds

pyroute2/netlink/nlsocket.py, tests/test_integration/test_lnst.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1068
=> nlsocket: fix marshal reference in the engine

docs/usage.rst
=> docs: avoid sudo pip install

Makefile, noxfile.py, pyroute2/loader.py, pyroute2/minimal.py, tests/test_repo/test_minimal.py
Use the static code instead of entry points
Bug-Url: https://github.com/svinota/pyroute2/issues/1076
=> Static library loader

noxfile.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1076
=> ci: cleanup build after nox lab session

examples/wifi/nl80211_set_type.py, pyroute2/iwutil.py
1. set_interface_type -- set possible type for wireless interface
2. get_interface_type -- get cuurent interface type
3. examples/wifi/nl80211_set_type -- exmple for work get/set_interface_type
=> iwutil: Add functional for get/set interface (by ifindex) type

pyroute2/netns/__init__.py
Provide loongarch64 syscall number for setns
=> provide loongarch support

noxfile.py
```
nox -e $session -- '{"fail_on_warnings": true}'
```
=> ci: add fail_on_warnings config option

pyroute2/ethtool/ioctl.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1112
=> ethtool: dynamic ioctl gstrings struct definition

pyroute2/iproute/linux.py
This is a follow-up to #1121 fixing the method arguments of `set_netnsid` to match the kernel netlink API.
For me it closes #1123, although it does **not** fix the usability of the `fd` arg.
=> iproute: fix set_netnsid implementation to work with NetNS

pyroute2/ndb/compat.py
error handling to default to ndb calls if ipdb returns errors related to #1132  
This adds capability without removing or altering existing functionality
=> Update compat.py to add try/except

pyroute2/netlink/diag/ss2.py
Is a problem for https://github.com/cherusk/prometheus_ss_exporter that uses ss2 as a module.
=> patch problematic classful flow data

Makefile
Bug-Url: https://github.com/svinota/pyroute2/issues/1117
=> makefile: add release target

pyroute2/ndb/objects/neighbour.py
issue: https://github.com/svinota/pyroute2/issues/1214
=> reorder af_bridge_fdb table indexes in a right way

pyroute2/iproute/linux.py
I respectfully submit this pull request which, in my opinion, contributes a small improvement to documentation.
=> iproute: improve 'state' keyword documentation

pyroute2/iproute/linux.py, tests/test_linux/test_tc/test_basic.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1232
=> iproute: support compat tc args

pyroute2/netlink/core.py, tests/test_linux/test_ipr/test_netns.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1226
=> iproute: respect the flags

pyroute2/iproute/linux.py, tests/test_core/test_ipr/test_route_async.py, tests/test_core/test_ipr/test_route_sync.py
* make show command eq dump
* add tests
Bug-Url: https://github.com/svinota/pyroute2/issues/1225
=> iproute: fix route filter

pyroute2/config/asyncio.py, requirements.dev.txt, tests/test_linux/test_ndb/test_altnames.py, tests/test_neutron/test_ip_lib.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1225
=> eventlet: provide additional socket properties

docs/_static/custom.css, docs/asyncio.rst, docs/index.rst, docs/iproute.rst, docs/iproute_intro.rst, docs/iproute_linux.rst, docs/iproute_netns.rst, docs/iproute_platforms.rst, docs/iproute_tc.rst, docs/usage.rst, noxfile.py, pyroute2/config/__init__.py, pyroute2/iproute/__init__.py, pyroute2/iproute/ipmock.py, pyroute2/iproute/linux.py, pyroute2/netlink/core.py, pyroute2/netlink/rtnl/iprsocket.py
+ fix python version for docs build, because 3.14 breaks sphinx' `literalinclude`
=> docs: add asyncio intro

pyroute2/__init__.py, pyroute2/ipdb/__init__.py, pyroute2/iproute/linux.py, pyroute2/ndb/objects/interface.py, pyroute2/requests/bridge.py, tests/test_integration/conftest.py, tests/test_integration/test_kuryr.py, tests/test_integration/test_octavia.py, tests/test_integration/test_os_vif.py, tests/test_integration/test_ovn_bgp_agent.py
=> ci: update integration tests

pyroute2/dhcp/hooks.py, pyroute2/fixtures/iproute.py, tests/test_linux/conftest.py, tests/test_linux/fixtures/interfaces.py, tests/test_linux/test_dhcp/conftest.py, tests/test_linux/test_dhcp/test_hooks.py
There are lots of ways for dhcp hooks to fail, they need more tests
=> dhcp: improve & properly test hooks

pyroute2/dhcp/client.py, pyroute2/dhcp/hooks.py, pyroute2/fixtures/iproute.py, pyroute2/ndb/objects/interface.py, tests/test_ci/test_fixtures.py, tests/test_linux/test_dhcp/test_cli.py, tests/test_linux/test_dhcp/test_hooks.py
* create unique netns nsname
* pushns(nsname)
* run test
* popns()
* cleanup
=> fixtures: setns_context

docs/usage.rst, pyroute2/dhcp/iface_status.py, pyroute2/fixtures/plan9.py, pyroute2/iproute/linux.py, pyroute2/netlink/core.py, pyroute2/netlink/nlsocket.py, pyroute2/plan9/client.py, pyroute2/plan9/server.py, tests/test_core/test_event_loop.py
Event loop initialization and retrieval.
Bug-Url: https://github.com/svinota/pyroute2/issues/1266
=> core: use_event_loop option

pyroute2/dhcp/__init__.py, pyroute2/dhcp/cli.py, pyroute2/dhcp/client.py, pyroute2/dhcp/dhcp4msg.py, pyroute2/dhcp/enums/dhcp.py, pyroute2/dhcp/fsm.py, pyroute2/dhcp/iface_status.py, pyroute2/dhcp/leases.py, pyroute2/dhcp/messages.py, pyroute2/dhcp/server_detector.py, pyroute2/dhcp/timers.py, pyroute2/ext/rawsocket.py, pyroute2/protocols/__init__.py, tests/test_linux/test_dhcp/test_encode.py, tests/test_linux/test_dhcp/test_integration.py, tests/test_linux/test_dhcp/test_parser.py
mypy does not return errors anymore for the dhcp module, and i found a bug in the process
=> dhcp: refactor typing, ip list decoding bug

pyroute2/iproute/linux.py, pyroute2/netlink/core.py, pyroute2/netlink/rtnl/iprsocket.py, tests/test_core/test_event_loop.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1266
Bug-Url: https://github.com/svinota/pyroute2/pull/1277
=> iproute: use_event_loop in sync version

pyroute2/dhcp/cli.py, pyroute2/dhcp/client.py, pyroute2/dhcp/timers.py, tests/test_linux/fixtures/dhcp_servers/__init__.py, tests/test_linux/test_dhcp/conftest.py, tests/test_linux/test_dhcp/test_cli.py, tests/test_linux/test_dhcp/test_integration.py
- SIGUSR1 triggers a renewal
- SIGUSR2 triggers a rebinding
- SIGHUP resets the client
=> dhcp client: add signal handlers to renew/rebind/reset the lease

pyroute2/requests/address.py, pyroute2/requests/main.py, tests/net_tools.py, tests/test_core/test_ipr/test_addr_async.py, tests/test_core/test_ipr/test_addr_sync.py, tests/test_unit/test_requests/test_address.py
Bug-Url: https://github.com/svinota/pyroute2/issues/752
=> fix preferred and valid lft

pyroute2/ndb/objects/interface.py, tests/test_linux/test_ndb/test_netns.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1181
=> ndb: update interface index after move to a netns

pyroute2/common.py, pyroute2/config/__init__.py, pyroute2/netns/__init__.py, pyroute2/process.py, tests/test_core/test_socket_create.py, tests/test_process/test_basic.py, tests/test_process/test_catastrophe.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1305
=> handle process exceptions

CHANGELOG.rst, pyroute2/iproute/linux.py
Final fixes before tagging the release.
=> release 0.9.1

pyroute2/iproute/__init__.py, pyroute2/iproute/darwin.py
I am working on the Vula(codeberg.org/vula) port to macOS, and adding this file seems to fix some of the errors related to general work.
Looking forward for your comments
=> Adding IPRoute class for darwin

docs/asyncio.rst, docs/index.rst, docs/threading.rst
Bug-Url: https://github.com/svinota/pyroute2/issues/1213
=> docs: add threading vs. fork documentation

.github/workflows/pull_request.yml, noxfile.py, pyroute2/netlink/core.py, pyroute2/netlink/rtnl/iprsocket.py, requirements.dev.txt
In order to provide compatibility.
Bug-Url: https://github.com/svinota/pyroute2/issues/1336
=> core: expose epid as an attribute

pyroute2/iproute/linux.py
Dont' ignore errno.EPERM and other codes.
=> iproute: improve exception handling in ensure()

noxfile.py, pyroute2/__init__.py, pyroute2/conntrack.py, pyroute2/iproute/linux.py, pyroute2/netlink/core.py, pyroute2/netlink/devlink/__init__.py, pyroute2/netlink/event/__init__.py, pyroute2/netlink/event/acpi_event.py, pyroute2/netlink/event/dquot.py, pyroute2/netlink/event/thermal.py, pyroute2/netlink/generic/__init__.py, pyroute2/netlink/generic/ethtool.py, pyroute2/netlink/generic/ipvs.py, pyroute2/netlink/generic/l2tp.py, pyroute2/netlink/generic/mptcp.py, pyroute2/netlink/generic/wireguard.py, pyroute2/netlink/nfnetlink/nfctsocket.py, pyroute2/netlink/nfnetlink/nftsocket.py, pyroute2/netlink/nl80211/__init__.py, pyroute2/netlink/nlsocket.py, pyroute2/netlink/taskstats/__init__.py, pyroute2/nftables/main.py, tests/test_core/test_statsd.py, tests/test_linux/test_devlink.py, tests/test_linux/test_diag.py, tests/test_linux/test_generic/test_l2tp.py
Async API classes, generic netlink protocols:
Related changes:
=> generic: async API

pyroute2/iwutil.py, tests/test_linux/test_iwutil.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1380
=> iwutil: fix get_interfaces_dict()

pyroute2/conntrack.py, pyroute2/netlink/nfnetlink/nfctsocket.py, tests/test_linux/test_conntrack.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1381
=> conntrack: add zone to dump and ConntrackEntry

noxfile.py, pyroute2/ndb/main.py, pyroute2/ndb/objects/interface.py, pyroute2/ndb/schema.py, pyroute2/ndb/sync_api.py, tests/test_core/test_ndb/test_schema.py
Bug-Url: https://github.com/svinota/pyroute2/issues/1364
=> ndb: snapshot cleanup on create

pyroute2/netlink/__init__.py, pyroute2/netlink/rtnl/ifinfmsg/__init__.py
The original PR + Ignore IFLA_ALLMULTI in NDB
Bug-Url: https://github.com/svinota/pyroute2/pull/1399
=> ifinfmsg: add IFLA_ALLMULTI flag

pyroute2/ipset.py, pyroute2/wiset.py, tests/test_linux/test_ipset.py, tests/test_linux/test_wiset.py
I implemented add() before but without method to remove an entry.
=> wiset: add delete() method and fix add method for ipset without IP address

pyroute2/netlink/rtnl/ndmsg.py
Update NDA list.
Link: https://github.com/torvalds/linux/blob/v6.8/net/core/neighbour.c#L1888
=> ndmsg: update nda list
